// EatFlow POS - Mock Data for Μαύρη Θάλασσα (Black Sea) Restaurant

import type {
  Table,
  Category,
  Product,
  Order,
  Zone,
  Modifier,
  Ingredient,
  Recipe,
  WasteEntry,
  Supplier,
  SupplierOrder,
  Customer,
  CustomerVisit,
  LoyaltySettings,
  StaffMember,
  Shift,
  ChecklistItem,
  StaffPerformance,
} from "./types";

export const initialZones: Zone[] = [
  { id: "zone1", name: "Εσωτερικό", color: "#3b82f6", order: 1 },
  { id: "zone2", name: "Βεράντα", color: "#22c55e", order: 2 },
  { id: "zone3", name: "Μπαρ", color: "#f59e0b", order: 3 },
];

export const initialTables: Table[] = [
  // Zone 1 - Εσωτερικό (left side of floor plan)
  {
    id: "t1",
    number: 1,
    capacity: 2,
    status: "available",
    zoneId: "zone1",
    x: 10,
    y: 15,
    shape: "round",
    rotation: 0,
  },
  {
    id: "t2",
    number: 2,
    capacity: 2,
    status: "available",
    zoneId: "zone1",
    x: 25,
    y: 15,
    shape: "round",
    rotation: 0,
  },
  {
    id: "t3",
    number: 3,
    capacity: 4,
    status: "available",
    zoneId: "zone1",
    x: 10,
    y: 45,
    shape: "square",
    rotation: 0,
  },
  {
    id: "t4",
    number: 4,
    capacity: 4,
    status: "available",
    zoneId: "zone1",
    x: 25,
    y: 45,
    shape: "square",
    rotation: 0,
  },
  {
    id: "t5",
    number: 5,
    capacity: 4,
    status: "available",
    zoneId: "zone1",
    x: 10,
    y: 75,
    shape: "square",
    rotation: 0,
  },
  {
    id: "t6",
    number: 6,
    capacity: 6,
    status: "available",
    zoneId: "zone1",
    x: 25,
    y: 75,
    shape: "rectangle",
    rotation: 0,
  },
  // Zone 2 - Βεράντα (right side of floor plan)
  {
    id: "t7",
    number: 7,
    capacity: 6,
    status: "available",
    zoneId: "zone2",
    x: 55,
    y: 15,
    shape: "rectangle",
    rotation: 0,
  },
  {
    id: "t8",
    number: 8,
    capacity: 2,
    status: "available",
    zoneId: "zone2",
    x: 75,
    y: 15,
    shape: "round",
    rotation: 0,
  },
  {
    id: "t9",
    number: 9,
    capacity: 4,
    status: "available",
    zoneId: "zone2",
    x: 55,
    y: 50,
    shape: "square",
    rotation: 0,
  },
  {
    id: "t10",
    number: 10,
    capacity: 4,
    status: "available",
    zoneId: "zone2",
    x: 75,
    y: 50,
    shape: "square",
    rotation: 0,
  },
  // Zone 3 - Μπαρ (bottom center)
  {
    id: "t11",
    number: 11,
    capacity: 6,
    status: "available",
    zoneId: "zone3",
    x: 55,
    y: 82,
    shape: "rectangle",
    rotation: 0,
  },
  {
    id: "t12",
    number: 12,
    capacity: 8,
    status: "available",
    zoneId: "zone3",
    x: 75,
    y: 82,
    shape: "rectangle",
    rotation: 0,
  },
];

export const initialCategories: Category[] = [
  { id: "cat1", name: "Ωμά", order: 1 },
  { id: "cat2", name: "Κρύα Ορεκτικά", order: 2 },
  { id: "cat3", name: "Ζεστά Ορεκτικά", order: 3 },
  { id: "cat4", name: "Ψητά Θαλασσινά", order: 4 },
  { id: "cat5", name: "Μαγειρευτά", order: 5 },
  { id: "cat6", name: "Ζυμαρικά", order: 6 },
  { id: "cat7", name: "Γλυκά", order: 7 },
];

export const initialModifiers: Modifier[] = [
  {
    id: "mod1",
    name: "Χωρίς κρεμμύδι",
    price: 0,
    categoryIds: ["cat2", "cat3", "cat5"],
  },
  {
    id: "mod2",
    name: "Χωρίς σάλτσα",
    price: 0,
    categoryIds: ["cat3", "cat4", "cat5", "cat6"],
  },
  {
    id: "mod3",
    name: "Extra λεμόνι",
    price: 0,
    categoryIds: ["cat1", "cat4"],
  },
  {
    id: "mod4",
    name: "Extra ελαιόλαδο",
    price: 0,
    categoryIds: ["cat1", "cat2", "cat4"],
  },
  {
    id: "mod5",
    name: "Well done",
    price: 0,
    categoryIds: ["cat4"],
  },
  {
    id: "mod6",
    name: "Medium",
    price: 0,
    categoryIds: ["cat4"],
  },
  {
    id: "mod7",
    name: "Χωρίς αλάτι",
    price: 0,
    categoryIds: ["cat1", "cat2", "cat3", "cat4", "cat5", "cat6"],
  },
  {
    id: "mod8",
    name: "Χωρίς γλουτένη",
    price: 0,
    categoryIds: ["cat3", "cat5", "cat6", "cat7"],
  },
  {
    id: "mod9",
    name: "Χωρίς λακτόζη",
    price: 0,
    categoryIds: ["cat2", "cat3", "cat5", "cat7"],
  },
  {
    id: "mod10",
    name: "Για μοίρασμα",
    price: 0,
    categoryIds: ["cat1", "cat2", "cat3", "cat7"],
  },
  {
    id: "mod11",
    name: "Extra σάλτσα",
    price: 1.5,
    categoryIds: ["cat6"],
  },
];

export const initialProducts: Product[] = [
  // Ωμά (cat1, cold)
  {
    id: "p1",
    name: "Καρπάτσιο Λαβρακιού",
    price: 16,
    categoryId: "cat1",
    description: "Φρέσκο φιλέτο λαβρακιού με ελαιόλαδο και λεμόνι",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p2",
    name: "Καρπάτσιο Μπαρμπουνιού",
    price: 18,
    categoryId: "cat1",
    description: "Φρέσκο μπαρμπούνι σε λεπτές φέτες",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p3",
    name: "Ταρτάρ Γαρίδας",
    price: 18,
    categoryId: "cat1",
    description: "Ωμή γαρίδα με αρωματικά",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  // Κρύα Ορεκτικά (cat2, cold)
  {
    id: "p4",
    name: "Ταραμοσαλάτα Λευκή",
    price: 12,
    categoryId: "cat2",
    description: "Σπιτική λευκή ταραμοσαλάτα",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p5",
    name: "Μελιτζανοσαλάτα",
    price: 8,
    categoryId: "cat2",
    description: "Καπνιστή μελιτζάνα με ελαιόλαδο",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p6",
    name: "Καβουροσαλάτα",
    price: 16,
    categoryId: "cat2",
    description: "Φρέσκο καβούρι σε σαλάτα",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p7",
    name: "Χτένια Ωμά",
    price: 22,
    categoryId: "cat2",
    description: "Φρέσκα χτένια με λεμόνι",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  // Ζεστά Ορεκτικά (cat3, hot)
  {
    id: "p8",
    name: "Σαγανάκι Γαρίδες",
    price: 18,
    categoryId: "cat3",
    description: "Γαρίδες σαγανάκι με φέτα και ντομάτα",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p9",
    name: "Αχνιστά Όστρακα",
    price: 16,
    categoryId: "cat3",
    description: "Όστρακα αχνιστά με κρασί",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p10",
    name: "Καλαμαράκια Τηγανητά",
    price: 14,
    categoryId: "cat3",
    description: "Τραγανά καλαμαράκια με λεμόνι",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p11",
    name: "Γαρίδες Τηγανητές",
    price: 18,
    categoryId: "cat3",
    description: "Τηγανητές γαρίδες με σάλτσα",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  // Ψητά Θαλασσινά (cat4, hot)
  {
    id: "p12",
    name: "Τσιπούρα",
    price: 75,
    categoryId: "cat4",
    description: "Φρέσκια τσιπούρα σχάρας (κιλό)",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p13",
    name: "Μπαρμπούνι",
    price: 85,
    categoryId: "cat4",
    description: "Φρέσκο μπαρμπούνι σχάρας (κιλό)",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p14",
    name: "Φαγκρί",
    price: 95,
    categoryId: "cat4",
    description: "Φρέσκο φαγκρί σχάρας (κιλό)",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p15",
    name: "Συναγρίδα",
    price: 95,
    categoryId: "cat4",
    description: "Φρέσκια συναγρίδα σχάρας (κιλό)",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p16",
    name: "Γαρίδες Θερμαϊκού",
    price: 95,
    categoryId: "cat4",
    description: "Φρέσκιες γαρίδες Θερμαϊκού σχάρας (κιλό)",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p17",
    name: "Καλαμάρι",
    price: 55,
    categoryId: "cat4",
    description: "Φρέσκο καλαμάρι σχάρας (κιλό)",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p18",
    name: "Χταπόδι",
    price: 48,
    categoryId: "cat4",
    description: "Χταπόδι σχάρας (κιλό)",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  // Μαγειρευτά (cat5, hot)
  {
    id: "p19",
    name: "Ψαρόσουπα",
    price: 90,
    categoryId: "cat5",
    description: "Παραδοσιακή ψαρόσουπα",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p20",
    name: "Φρικασέ",
    price: 120,
    categoryId: "cat5",
    description: "Φρικασέ θαλασσινών",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p21",
    name: "Κοκκινιστό",
    price: 120,
    categoryId: "cat5",
    description: "Θαλασσινά κοκκινιστά",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p22",
    name: "Πλακί",
    price: 140,
    categoryId: "cat5",
    description: "Ψάρι πλακί στο φούρνο",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  // Ζυμαρικά (cat6, hot)
  {
    id: "p23",
    name: "Γαριδομακαρονάδα",
    price: 28,
    categoryId: "cat6",
    description: "Λιγκουίνι με γαρίδες και σάλτσα ντομάτας",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p24",
    name: "Αστακομακαρονάδα",
    price: 45,
    categoryId: "cat6",
    description: "Λιγκουίνι με αστακό",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  // Γλυκά (cat7, dessert)
  {
    id: "p25",
    name: "Μπακλαβάς",
    price: 20,
    categoryId: "cat7",
    description: "Παραδοσιακός μπακλαβάς με φύλλο κρούστας",
    vatRate: 13,
    available: true,
    station: "dessert",
    modifierIds: [],
  },
  {
    id: "p26",
    name: "Τιραμισού",
    price: 14,
    categoryId: "cat7",
    description: "Κλασικό ιταλικό τιραμισού",
    vatRate: 13,
    available: true,
    station: "dessert",
    modifierIds: [],
  },
  {
    id: "p27",
    name: "Lemon Bar",
    price: 12,
    categoryId: "cat7",
    description: "Lemon bar με βουτυράτη βάση",
    vatRate: 13,
    available: true,
    station: "dessert",
    modifierIds: [],
  },
  {
    id: "p28",
    name: "Cheesecake",
    price: 14,
    categoryId: "cat7",
    description: "New York cheesecake",
    vatRate: 13,
    available: true,
    station: "dessert",
    modifierIds: [],
  },
];

export const initialOrders: Order[] = [];

// === Inventory Data ===

export const initialIngredients: Ingredient[] = [
  // Seafood
  {
    id: "ing1",
    name: "Τσιπούρα",
    unit: "kg",
    currentStock: 15,
    minStock: 5,
    costPerUnit: 18,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing2",
    name: "Μπαρμπούνι",
    unit: "kg",
    currentStock: 8,
    minStock: 3,
    costPerUnit: 22,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing3",
    name: "Φαγκρί",
    unit: "kg",
    currentStock: 6,
    minStock: 2,
    costPerUnit: 25,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing4",
    name: "Συναγρίδα",
    unit: "kg",
    currentStock: 2,
    minStock: 2,
    costPerUnit: 28,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing5",
    name: "Γαρίδες Θερμαϊκού",
    unit: "kg",
    currentStock: 10,
    minStock: 3,
    costPerUnit: 32,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing6",
    name: "Καλαμάρι",
    unit: "kg",
    currentStock: 12,
    minStock: 4,
    costPerUnit: 14,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing7",
    name: "Χταπόδι",
    unit: "kg",
    currentStock: 8,
    minStock: 3,
    costPerUnit: 16,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing8",
    name: "Λαβράκι φιλέτο",
    unit: "kg",
    currentStock: 6,
    minStock: 2,
    costPerUnit: 20,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing9",
    name: "Καβούρι",
    unit: "kg",
    currentStock: 1.5,
    minStock: 1,
    costPerUnit: 35,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing10",
    name: "Χτένια",
    unit: "kg",
    currentStock: 4,
    minStock: 2,
    costPerUnit: 28,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing11",
    name: "Όστρακα",
    unit: "kg",
    currentStock: 5,
    minStock: 2,
    costPerUnit: 18,
    supplierId: "sup1",
    category: "seafood",
  },
  // Vegetables
  {
    id: "ing12",
    name: "Ντομάτα",
    unit: "kg",
    currentStock: 20,
    minStock: 5,
    costPerUnit: 2.5,
    supplierId: "sup2",
    category: "vegetables",
  },
  {
    id: "ing13",
    name: "Μελιτζάνα",
    unit: "kg",
    currentStock: 8,
    minStock: 3,
    costPerUnit: 3,
    supplierId: "sup2",
    category: "vegetables",
  },
  {
    id: "ing14",
    name: "Πατάτα",
    unit: "kg",
    currentStock: 25,
    minStock: 8,
    costPerUnit: 1.5,
    supplierId: "sup2",
    category: "vegetables",
  },
  {
    id: "ing15",
    name: "Σέλινο",
    unit: "kg",
    currentStock: 5,
    minStock: 2,
    costPerUnit: 3,
    supplierId: "sup2",
    category: "vegetables",
  },
  {
    id: "ing16",
    name: "Κρεμμύδι",
    unit: "kg",
    currentStock: 15,
    minStock: 5,
    costPerUnit: 1.5,
    supplierId: "sup2",
    category: "vegetables",
  },
  {
    id: "ing17",
    name: "Λεμόνια",
    unit: "kg",
    currentStock: 10,
    minStock: 3,
    costPerUnit: 3,
    supplierId: "sup2",
    category: "vegetables",
  },
  {
    id: "ing18",
    name: "Μανιτάρια Portobello",
    unit: "kg",
    currentStock: 4,
    minStock: 2,
    costPerUnit: 8,
    supplierId: "sup2",
    category: "vegetables",
  },
  // Dairy
  {
    id: "ing19",
    name: "Αυγά",
    unit: "pcs",
    currentStock: 60,
    minStock: 20,
    costPerUnit: 0.35,
    supplierId: "sup3",
    category: "dairy",
  },
  {
    id: "ing20",
    name: "Φέτα",
    unit: "kg",
    currentStock: 5,
    minStock: 2,
    costPerUnit: 12,
    supplierId: "sup3",
    category: "dairy",
  },
  // Dry
  {
    id: "ing21",
    name: "Ελαιόλαδο",
    unit: "lt",
    currentStock: 20,
    minStock: 5,
    costPerUnit: 8,
    category: "dry",
  },
  {
    id: "ing22",
    name: "Αλεύρι",
    unit: "kg",
    currentStock: 10,
    minStock: 3,
    costPerUnit: 1.2,
    category: "dry",
  },
  {
    id: "ing23",
    name: "Ζυμαρικά Λιγκουίνι",
    unit: "kg",
    currentStock: 8,
    minStock: 3,
    costPerUnit: 3.5,
    category: "dry",
  },
  {
    id: "ing24",
    name: "Σάλτσα Ντομάτας",
    unit: "lt",
    currentStock: 10,
    minStock: 3,
    costPerUnit: 2.5,
    category: "dry",
  },
  {
    id: "ing25",
    name: "Πελτές",
    unit: "kg",
    currentStock: 5,
    minStock: 2,
    costPerUnit: 4,
    category: "dry",
  },
  {
    id: "ing26",
    name: "Ταραμάς",
    unit: "kg",
    currentStock: 3,
    minStock: 1,
    costPerUnit: 25,
    category: "dry",
  },
  {
    id: "ing27",
    name: "Φύλλο Κρούστας",
    unit: "pcs",
    currentStock: 20,
    minStock: 5,
    costPerUnit: 1.5,
    category: "dry",
  },
  {
    id: "ing28",
    name: "Μυρωδικά mix",
    unit: "kg",
    currentStock: 2,
    minStock: 0.5,
    costPerUnit: 15,
    category: "dry",
  },
  // Drinks
  {
    id: "ing29",
    name: "Κρασί Λευκό χύμα",
    unit: "lt",
    currentStock: 30,
    minStock: 10,
    costPerUnit: 4,
    supplierId: "sup4",
    category: "drinks",
  },
  {
    id: "ing30",
    name: "Κρασί Κόκκινο χύμα",
    unit: "lt",
    currentStock: 20,
    minStock: 8,
    costPerUnit: 4.5,
    supplierId: "sup4",
    category: "drinks",
  },
];

export const initialRecipes: Recipe[] = [
  // p1 - Καρπάτσιο Λαβρακιού
  {
    id: "rec1",
    productId: "p1",
    ingredients: [
      { ingredientId: "ing8", quantity: 0.15, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.02, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.05, unit: "kg" },
    ],
    prepTime: 10,
    portionSize: "1 μερίδα",
  },
  // p2 - Καρπάτσιο Μπαρμπουνιού
  {
    id: "rec2",
    productId: "p2",
    ingredients: [
      { ingredientId: "ing2", quantity: 0.18, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.02, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.05, unit: "kg" },
    ],
    prepTime: 10,
    portionSize: "1 μερίδα",
  },
  // p3 - Ταρτάρ Γαρίδας
  {
    id: "rec3",
    productId: "p3",
    ingredients: [
      { ingredientId: "ing5", quantity: 0.18, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.02, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.03, unit: "kg" },
      { ingredientId: "ing28", quantity: 0.005, unit: "kg" },
    ],
    prepTime: 12,
    portionSize: "1 μερίδα",
  },
  // p4 - Ταραμοσαλάτα Λευκή
  {
    id: "rec4",
    productId: "p4",
    ingredients: [
      { ingredientId: "ing26", quantity: 0.08, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.03, unit: "kg" },
    ],
    prepTime: 15,
    portionSize: "1 μερίδα",
  },
  // p5 - Μελιτζανοσαλάτα
  {
    id: "rec5",
    productId: "p5",
    ingredients: [
      { ingredientId: "ing13", quantity: 0.25, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.03, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.02, unit: "kg" },
    ],
    prepTime: 30,
    portionSize: "1 μερίδα",
  },
  // p6 - Καβουροσαλάτα
  {
    id: "rec6",
    productId: "p6",
    ingredients: [
      { ingredientId: "ing9", quantity: 0.15, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.02, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.03, unit: "kg" },
      { ingredientId: "ing12", quantity: 0.05, unit: "kg" },
    ],
    prepTime: 20,
    portionSize: "1 μερίδα",
  },
  // p7 - Χτένια Ωμά
  {
    id: "rec7",
    productId: "p7",
    ingredients: [
      { ingredientId: "ing10", quantity: 0.2, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.02, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.03, unit: "kg" },
    ],
    prepTime: 8,
    portionSize: "1 μερίδα",
  },
  // p8 - Σαγανάκι Γαρίδες
  {
    id: "rec8",
    productId: "p8",
    ingredients: [
      { ingredientId: "ing5", quantity: 0.2, unit: "kg" },
      { ingredientId: "ing20", quantity: 0.05, unit: "kg" },
      { ingredientId: "ing12", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.03, unit: "lt" },
      { ingredientId: "ing24", quantity: 0.05, unit: "lt" },
    ],
    prepTime: 15,
    portionSize: "1 μερίδα",
  },
  // p9 - Αχνιστά Όστρακα
  {
    id: "rec9",
    productId: "p9",
    ingredients: [
      { ingredientId: "ing11", quantity: 0.3, unit: "kg" },
      { ingredientId: "ing29", quantity: 0.1, unit: "lt" },
      { ingredientId: "ing21", quantity: 0.02, unit: "lt" },
      { ingredientId: "ing28", quantity: 0.005, unit: "kg" },
    ],
    prepTime: 12,
    portionSize: "1 μερίδα",
  },
  // p10 - Καλαμαράκια Τηγανητά
  {
    id: "rec10",
    productId: "p10",
    ingredients: [
      { ingredientId: "ing6", quantity: 0.25, unit: "kg" },
      { ingredientId: "ing22", quantity: 0.05, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.1, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.03, unit: "kg" },
    ],
    prepTime: 10,
    portionSize: "1 μερίδα",
  },
  // p11 - Γαρίδες Τηγανητές
  {
    id: "rec11",
    productId: "p11",
    ingredients: [
      { ingredientId: "ing5", quantity: 0.25, unit: "kg" },
      { ingredientId: "ing22", quantity: 0.05, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.1, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.03, unit: "kg" },
    ],
    prepTime: 10,
    portionSize: "1 μερίδα",
  },
  // p12 - Τσιπούρα (per kg)
  {
    id: "rec12",
    productId: "p12",
    ingredients: [
      { ingredientId: "ing1", quantity: 1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing28", quantity: 0.01, unit: "kg" },
    ],
    prepTime: 20,
    portionSize: "1 κιλό",
  },
  // p13 - Μπαρμπούνι (per kg)
  {
    id: "rec13",
    productId: "p13",
    ingredients: [
      { ingredientId: "ing2", quantity: 1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing28", quantity: 0.01, unit: "kg" },
    ],
    prepTime: 15,
    portionSize: "1 κιλό",
  },
  // p14 - Φαγκρί (per kg)
  {
    id: "rec14",
    productId: "p14",
    ingredients: [
      { ingredientId: "ing3", quantity: 1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing28", quantity: 0.01, unit: "kg" },
    ],
    prepTime: 25,
    portionSize: "1 κιλό",
  },
  // p15 - Συναγρίδα (per kg)
  {
    id: "rec15",
    productId: "p15",
    ingredients: [
      { ingredientId: "ing4", quantity: 1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing28", quantity: 0.01, unit: "kg" },
    ],
    prepTime: 25,
    portionSize: "1 κιλό",
  },
  // p16 - Γαρίδες Θερμαϊκού (per kg)
  {
    id: "rec16",
    productId: "p16",
    ingredients: [
      { ingredientId: "ing5", quantity: 1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
    ],
    prepTime: 15,
    portionSize: "1 κιλό",
  },
  // p17 - Καλαμάρι (per kg)
  {
    id: "rec17",
    productId: "p17",
    ingredients: [
      { ingredientId: "ing6", quantity: 1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing28", quantity: 0.01, unit: "kg" },
    ],
    prepTime: 20,
    portionSize: "1 κιλό",
  },
  // p18 - Χταπόδι (per kg)
  {
    id: "rec18",
    productId: "p18",
    ingredients: [
      { ingredientId: "ing7", quantity: 1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
    ],
    prepTime: 45,
    portionSize: "1 κιλό",
  },
  // p19 - Ψαρόσουπα
  {
    id: "rec19",
    productId: "p19",
    ingredients: [
      { ingredientId: "ing1", quantity: 0.5, unit: "kg" },
      { ingredientId: "ing3", quantity: 0.3, unit: "kg" },
      { ingredientId: "ing14", quantity: 0.2, unit: "kg" },
      { ingredientId: "ing15", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing16", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing17", quantity: 0.15, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing19", quantity: 2, unit: "pcs" },
    ],
    prepTime: 60,
    portionSize: "4 μερίδες",
  },
  // p20 - Φρικασέ
  {
    id: "rec20",
    productId: "p20",
    ingredients: [
      { ingredientId: "ing1", quantity: 0.6, unit: "kg" },
      { ingredientId: "ing5", quantity: 0.3, unit: "kg" },
      { ingredientId: "ing15", quantity: 0.15, unit: "kg" },
      { ingredientId: "ing16", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.08, unit: "lt" },
      { ingredientId: "ing19", quantity: 3, unit: "pcs" },
      { ingredientId: "ing28", quantity: 0.02, unit: "kg" },
    ],
    prepTime: 50,
    portionSize: "4 μερίδες",
  },
  // p21 - Κοκκινιστό
  {
    id: "rec21",
    productId: "p21",
    ingredients: [
      { ingredientId: "ing1", quantity: 0.5, unit: "kg" },
      { ingredientId: "ing6", quantity: 0.3, unit: "kg" },
      { ingredientId: "ing24", quantity: 0.3, unit: "lt" },
      { ingredientId: "ing25", quantity: 0.05, unit: "kg" },
      { ingredientId: "ing16", quantity: 0.15, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.08, unit: "lt" },
      { ingredientId: "ing28", quantity: 0.02, unit: "kg" },
    ],
    prepTime: 55,
    portionSize: "4 μερίδες",
  },
  // p22 - Πλακί
  {
    id: "rec22",
    productId: "p22",
    ingredients: [
      { ingredientId: "ing3", quantity: 0.8, unit: "kg" },
      { ingredientId: "ing12", quantity: 0.3, unit: "kg" },
      { ingredientId: "ing16", quantity: 0.15, unit: "kg" },
      { ingredientId: "ing14", quantity: 0.3, unit: "kg" },
      { ingredientId: "ing15", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.1, unit: "lt" },
      { ingredientId: "ing24", quantity: 0.2, unit: "lt" },
      { ingredientId: "ing28", quantity: 0.02, unit: "kg" },
    ],
    prepTime: 60,
    portionSize: "4 μερίδες",
  },
  // p23 - Γαριδομακαρονάδα
  {
    id: "rec23",
    productId: "p23",
    ingredients: [
      { ingredientId: "ing5", quantity: 0.3, unit: "kg" },
      { ingredientId: "ing23", quantity: 0.2, unit: "kg" },
      { ingredientId: "ing24", quantity: 0.1, unit: "lt" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing16", quantity: 0.03, unit: "kg" },
    ],
    prepTime: 25,
    portionSize: "1 μερίδα",
  },
  // p24 - Αστακομακαρονάδα
  {
    id: "rec24",
    productId: "p24",
    ingredients: [
      { ingredientId: "ing5", quantity: 0.4, unit: "kg" },
      { ingredientId: "ing23", quantity: 0.25, unit: "kg" },
      { ingredientId: "ing24", quantity: 0.15, unit: "lt" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing16", quantity: 0.03, unit: "kg" },
      { ingredientId: "ing12", quantity: 0.08, unit: "kg" },
      { ingredientId: "ing28", quantity: 0.01, unit: "kg" },
    ],
    prepTime: 35,
    portionSize: "1 μερίδα",
  },
  // p25 - Μπακλαβάς
  {
    id: "rec25",
    productId: "p25",
    ingredients: [
      { ingredientId: "ing27", quantity: 3, unit: "pcs" },
      { ingredientId: "ing19", quantity: 1, unit: "pcs" },
    ],
    prepTime: 5,
    portionSize: "1 μερίδα",
  },
  // p26 - Τιραμισού
  {
    id: "rec26",
    productId: "p26",
    ingredients: [{ ingredientId: "ing19", quantity: 2, unit: "pcs" }],
    prepTime: 5,
    portionSize: "1 μερίδα",
  },
  // p27 - Lemon Bar
  {
    id: "rec27",
    productId: "p27",
    ingredients: [
      { ingredientId: "ing19", quantity: 1, unit: "pcs" },
      { ingredientId: "ing17", quantity: 0.05, unit: "kg" },
      { ingredientId: "ing22", quantity: 0.03, unit: "kg" },
    ],
    prepTime: 5,
    portionSize: "1 μερίδα",
  },
  // p28 - Cheesecake
  {
    id: "rec28",
    productId: "p28",
    ingredients: [{ ingredientId: "ing19", quantity: 1, unit: "pcs" }],
    prepTime: 5,
    portionSize: "1 μερίδα",
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: "sup1",
    name: "Ιχθυοπωλείο Θερμαϊκός",
    phone: "2310-555-001",
    categories: ["seafood"],
  },
  {
    id: "sup2",
    name: "Λαχαναγορά Κεντρική",
    phone: "2310-555-002",
    categories: ["vegetables"],
  },
  {
    id: "sup3",
    name: "Γαλακτοκομικά Μακεδονίας",
    phone: "2310-555-003",
    categories: ["dairy"],
  },
  {
    id: "sup4",
    name: "Οινοποιείο Τσάνταλη",
    phone: "2310-555-004",
    categories: ["drinks"],
  },
];

export const initialSupplierOrders: SupplierOrder[] = [];

export const initialWasteLog: WasteEntry[] = [
  {
    id: "w1",
    ingredientId: "ing5",
    quantity: 0.5,
    reason: "expired",
    date: "2026-03-25T10:00:00.000Z",
    notes: "Γαρίδες ημέρας - δεν πουλήθηκαν",
  },
  {
    id: "w2",
    ingredientId: "ing12",
    quantity: 2,
    reason: "damaged",
    date: "2026-03-25T11:30:00.000Z",
    notes: "Χτυπημένες ντομάτες από μεταφορά",
  },
  {
    id: "w3",
    ingredientId: "ing11",
    quantity: 0.3,
    reason: "overproduction",
    date: "2026-03-26T21:00:00.000Z",
    notes: "Περίσσεψαν από αχνιστά",
  },
  {
    id: "w4",
    ingredientId: "ing6",
    quantity: 0.2,
    reason: "returned",
    date: "2026-03-26T20:30:00.000Z",
    notes: "Πελάτης επέστρεψε πιάτο",
  },
];

// === CRM & Loyalty Data ===

// Helper to compute ISO date strings relative to "today"
function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  // Return just the month-day portion as a birthday (year-agnostic, stored as MM-DD with a fake year)
  return `1990-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

export const initialCustomers: Customer[] = [
  {
    id: "cust-01",
    name: "Γιάννης Κωνσταντίνου",
    phone: "6971234567",
    email: "giannis.k@email.gr",
    birthday: daysFromNow(5),
    notes: "Προτιμά τραπέζι στη βεράντα",
    isVip: true,
    allergies: [],
    tags: ["Τακτικός", "Κρασί lover"],
    loyaltyPoints: 210,
    stampCount: 5,
    createdAt: daysAgo(180),
  },
  {
    id: "cust-02",
    name: "Μαρία Παπαδοπούλου",
    phone: "6982345678",
    email: "maria.p@email.gr",
    birthday: "1985-08-15",
    notes: "Business lunches — ζητάει πάντα απόδειξη εταιρείας",
    isVip: true,
    allergies: ["Γλουτένη"],
    tags: ["Business lunch"],
    loyaltyPoints: 140,
    stampCount: 4,
    createdAt: daysAgo(150),
  },
  {
    id: "cust-03",
    name: "Νίκος Δημητρίου",
    phone: "6993456789",
    email: "nikos.d@email.gr",
    birthday: "1978-11-22",
    notes: "",
    isVip: false,
    allergies: ["Ξηροί Καρποί", "Λακτόζη"],
    tags: [],
    loyaltyPoints: 72,
    stampCount: 2,
    createdAt: daysAgo(120),
  },
  {
    id: "cust-04",
    name: "Ελένη Γεωργίου",
    phone: "6944567890",
    email: "eleni.g@email.gr",
    birthday: daysFromNow(2),
    notes: "Αγαπημένη πελάτισσα — foodie blogger",
    isVip: true,
    allergies: [],
    tags: ["Foodie", "Τακτικός"],
    loyaltyPoints: 320,
    stampCount: 6,
    createdAt: daysAgo(365),
  },
  {
    id: "cust-05",
    name: "Δημήτρης Αλεξίου",
    phone: "6955678901",
    notes: "",
    isVip: false,
    allergies: [],
    tags: [],
    loyaltyPoints: 42,
    stampCount: 3,
    createdAt: daysAgo(90),
  },
  {
    id: "cust-06",
    name: "Σοφία Νικολάου",
    phone: "6966789012",
    email: "sofia.n@email.gr",
    birthday: "1992-03-10",
    notes: "Αποφεύγει θαλασσινά — παραγγέλνει ζυμαρικά/κρέας",
    isVip: false,
    allergies: ["Θαλασσινά"],
    tags: [],
    loyaltyPoints: 96,
    stampCount: 5,
    createdAt: daysAgo(200),
  },
  {
    id: "cust-07",
    name: "Κώστας Παπανικολάου",
    phone: "6977890123",
    notes: "",
    isVip: false,
    allergies: [],
    tags: ["Νέος"],
    loyaltyPoints: 28,
    stampCount: 1,
    createdAt: daysAgo(30),
  },
  {
    id: "cust-08",
    name: "Αναστασία Βασιλείου",
    phone: "6988901234",
    email: "anastasia.v@email.gr",
    birthday: "1980-06-05",
    notes: "Πάντα με παρέα 4+ ατόμων",
    isVip: true,
    allergies: [],
    tags: ["Τακτικός"],
    loyaltyPoints: 180,
    stampCount: 7,
    createdAt: daysAgo(270),
  },
  {
    id: "cust-09",
    name: "Πέτρος Ιωάννου",
    phone: "6939012345",
    notes: "",
    isVip: false,
    allergies: [],
    tags: [],
    loyaltyPoints: 18,
    stampCount: 1,
    createdAt: daysAgo(100),
  },
  {
    id: "cust-10",
    name: "Χριστίνα Μιχαήλ",
    phone: "6920123456",
    email: "christina.m@email.gr",
    birthday: "1995-12-01",
    notes: "",
    isVip: false,
    allergies: [],
    tags: [],
    loyaltyPoints: 12,
    stampCount: 0,
    createdAt: daysAgo(80),
  },
  {
    id: "cust-11",
    name: "Αλέξανδρος Θεοδώρου",
    phone: "6941234567",
    email: "alex.th@email.gr",
    birthday: "1975-09-18",
    notes: "Στέλεχος εταιρείας — business meals",
    isVip: false,
    allergies: [],
    tags: ["Business lunch"],
    loyaltyPoints: 60,
    stampCount: 3,
    createdAt: daysAgo(160),
  },
  {
    id: "cust-12",
    name: "Κατερίνα Σταματίου",
    phone: "6952345678",
    birthday: "1988-04-25",
    notes: "Αλλεργία στα αυγά — προσοχή σε γλυκά",
    isVip: false,
    allergies: ["Αυγά"],
    tags: [],
    loyaltyPoints: 38,
    stampCount: 2,
    createdAt: daysAgo(110),
  },
  {
    id: "cust-13",
    name: "Θανάσης Πολυχρόνου",
    phone: "6963456789",
    notes: "",
    isVip: false,
    allergies: [],
    tags: [],
    loyaltyPoints: 7,
    stampCount: 0,
    createdAt: daysAgo(95),
  },
  {
    id: "cust-14",
    name: "Βασιλική Οικονόμου",
    phone: "6974567890",
    email: "vasiliki.o@email.gr",
    birthday: "1983-07-12",
    notes: "Κοντά σε stamp reward!",
    isVip: false,
    allergies: [],
    tags: [],
    loyaltyPoints: 55,
    stampCount: 8,
    createdAt: daysAgo(140),
  },
  {
    id: "cust-15",
    name: "Γεώργιος Αθανασίου",
    phone: "6985678901",
    email: "george.a@email.gr",
    birthday: "1990-01-30",
    notes: "Κοντά σε point reward",
    isVip: false,
    allergies: [],
    tags: [],
    loyaltyPoints: 85,
    stampCount: 4,
    createdAt: daysAgo(130),
  },
];

// Menu item names for visit history (realistic product names from the menu)
const menuItems = [
  "Καρπάτσιο Λαβρακιού",
  "Καρπάτσιο Μπαρμπουνιού",
  "Ταρτάρ Γαρίδας",
  "Ταραμοσαλάτα Λευκή",
  "Μελιτζανοσαλάτα",
  "Καβουροσαλάτα",
  "Χτένια Ωμά",
  "Σαγανάκι Γαρίδες",
  "Αχνιστά Όστρακα",
  "Καλαμαράκια Τηγανητά",
  "Γαρίδες Τηγανητές",
  "Τσιπούρα",
  "Μπαρμπούνι",
  "Φαγκρί",
  "Συναγρίδα",
  "Γαρίδες Θερμαϊκού",
  "Καλαμάρι",
  "Χταπόδι",
  "Ψαρόσουπα",
  "Γαριδομακαρονάδα",
  "Αστακομακαρονάδα",
  "Μπακλαβάς",
  "Τιραμισού",
  "Lemon Bar",
  "Cheesecake",
];

export const initialCustomerVisits: CustomerVisit[] = [
  // Γιάννης Κωνσταντίνου (cust-01) — 25 visits, ~€2,100 total
  {
    id: "cv-001",
    customerId: "cust-01",
    orderId: "mock-order-001",
    date: daysAgo(2),
    tableNumber: 7,
    total: 95,
    items: ["Τσιπούρα", "Ταραμοσαλάτα Λευκή", "Τιραμισού"],
  },
  {
    id: "cv-002",
    customerId: "cust-01",
    orderId: "mock-order-002",
    date: daysAgo(5),
    tableNumber: 9,
    total: 78,
    items: ["Καρπάτσιο Λαβρακιού", "Σαγανάκι Γαρίδες", "Cheesecake"],
  },
  {
    id: "cv-003",
    customerId: "cust-01",
    orderId: "mock-order-003",
    date: daysAgo(9),
    tableNumber: 7,
    total: 110,
    items: ["Φαγκρί", "Χτένια Ωμά", "Μπακλαβάς"],
  },
  {
    id: "cv-004",
    customerId: "cust-01",
    orderId: "mock-order-004",
    date: daysAgo(14),
    tableNumber: 10,
    total: 85,
    items: ["Γαριδομακαρονάδα", "Καλαμαράκια Τηγανητά"],
  },
  {
    id: "cv-005",
    customerId: "cust-01",
    orderId: "mock-order-005",
    date: daysAgo(20),
    tableNumber: 7,
    total: 92,
    items: ["Τσιπούρα", "Μελιτζανοσαλάτα"],
  },
  {
    id: "cv-006",
    customerId: "cust-01",
    orderId: "mock-order-006",
    date: daysAgo(27),
    tableNumber: 8,
    total: 75,
    items: ["Χταπόδι", "Ταραμοσαλάτα Λευκή"],
  },
  {
    id: "cv-007",
    customerId: "cust-01",
    orderId: "mock-order-007",
    date: daysAgo(35),
    tableNumber: 7,
    total: 88,
    items: ["Καρπάτσιο Λαβρακιού", "Γαρίδες Θερμαϊκού"],
  },
  {
    id: "cv-008",
    customerId: "cust-01",
    orderId: "mock-order-008",
    date: daysAgo(42),
    tableNumber: 9,
    total: 65,
    items: ["Αστακομακαρονάδα", "Lemon Bar"],
  },
  {
    id: "cv-009",
    customerId: "cust-01",
    orderId: "mock-order-009",
    date: daysAgo(50),
    tableNumber: 7,
    total: 102,
    items: ["Συναγρίδα", "Καβουροσαλάτα"],
  },
  {
    id: "cv-010",
    customerId: "cust-01",
    orderId: "mock-order-010",
    date: daysAgo(58),
    tableNumber: 10,
    total: 78,
    items: ["Τσιπούρα", "Τιραμισού"],
  },
  {
    id: "cv-011",
    customerId: "cust-01",
    orderId: "mock-order-011",
    date: daysAgo(63),
    tableNumber: 7,
    total: 90,
    items: ["Μπαρμπούνι", "Σαγανάκι Γαρίδες"],
  },
  {
    id: "cv-012",
    customerId: "cust-01",
    orderId: "mock-order-012",
    date: daysAgo(70),
    tableNumber: 8,
    total: 72,
    items: ["Γαριδομακαρονάδα", "Μελιτζανοσαλάτα"],
  },
  {
    id: "cv-013",
    customerId: "cust-01",
    orderId: "mock-order-013",
    date: daysAgo(78),
    tableNumber: 7,
    total: 85,
    items: ["Καλαμάρι", "Ταρτάρ Γαρίδας"],
  },

  // Μαρία Παπαδοπούλου (cust-02) — 18 visits, ~€1,400 total
  {
    id: "cv-014",
    customerId: "cust-02",
    orderId: "mock-order-014",
    date: daysAgo(3),
    tableNumber: 3,
    total: 82,
    items: ["Γαριδομακαρονάδα", "Καβουροσαλάτα", "Cheesecake"],
  },
  {
    id: "cv-015",
    customerId: "cust-02",
    orderId: "mock-order-015",
    date: daysAgo(8),
    tableNumber: 4,
    total: 78,
    items: ["Τσιπούρα", "Μελιτζανοσαλάτα"],
  },
  {
    id: "cv-016",
    customerId: "cust-02",
    orderId: "mock-order-016",
    date: daysAgo(15),
    tableNumber: 3,
    total: 95,
    items: ["Φαγκρί", "Ταραμοσαλάτα Λευκή"],
  },
  {
    id: "cv-017",
    customerId: "cust-02",
    orderId: "mock-order-017",
    date: daysAgo(22),
    tableNumber: 5,
    total: 68,
    items: ["Αστακομακαρονάδα"],
  },
  {
    id: "cv-018",
    customerId: "cust-02",
    orderId: "mock-order-018",
    date: daysAgo(30),
    tableNumber: 3,
    total: 72,
    items: ["Γαρίδες Τηγανητές", "Lemon Bar"],
  },
  {
    id: "cv-019",
    customerId: "cust-02",
    orderId: "mock-order-019",
    date: daysAgo(38),
    tableNumber: 4,
    total: 85,
    items: ["Καρπάτσιο Μπαρμπουνιού", "Σαγανάκι Γαρίδες"],
  },
  {
    id: "cv-020",
    customerId: "cust-02",
    orderId: "mock-order-020",
    date: daysAgo(45),
    tableNumber: 3,
    total: 76,
    items: ["Γαριδομακαρονάδα", "Τιραμισού"],
  },
  {
    id: "cv-021",
    customerId: "cust-02",
    orderId: "mock-order-021",
    date: daysAgo(55),
    tableNumber: 6,
    total: 90,
    items: ["Μπαρμπούνι", "Χτένια Ωμά"],
  },
  {
    id: "cv-022",
    customerId: "cust-02",
    orderId: "mock-order-022",
    date: daysAgo(65),
    tableNumber: 3,
    total: 62,
    items: ["Καλαμαράκια Τηγανητά", "Μελιτζανοσαλάτα"],
  },
  {
    id: "cv-023",
    customerId: "cust-02",
    orderId: "mock-order-023",
    date: daysAgo(75),
    tableNumber: 4,
    total: 88,
    items: ["Τσιπούρα", "Καβουροσαλάτα"],
  },

  // Νίκος Δημητρίου (cust-03) — 12 visits, ~€850 total
  {
    id: "cv-024",
    customerId: "cust-03",
    orderId: "mock-order-024",
    date: daysAgo(4),
    tableNumber: 1,
    total: 72,
    items: ["Γαριδομακαρονάδα", "Μελιτζανοσαλάτα"],
  },
  {
    id: "cv-025",
    customerId: "cust-03",
    orderId: "mock-order-025",
    date: daysAgo(12),
    tableNumber: 2,
    total: 68,
    items: ["Καλαμαράκια Τηγανητά", "Ταραμοσαλάτα Λευκή"],
  },
  {
    id: "cv-026",
    customerId: "cust-03",
    orderId: "mock-order-026",
    date: daysAgo(21),
    tableNumber: 1,
    total: 85,
    items: ["Χταπόδι", "Σαγανάκι Γαρίδες"],
  },
  {
    id: "cv-027",
    customerId: "cust-03",
    orderId: "mock-order-027",
    date: daysAgo(33),
    tableNumber: 5,
    total: 62,
    items: ["Αχνιστά Όστρακα", "Lemon Bar"],
  },
  {
    id: "cv-028",
    customerId: "cust-03",
    orderId: "mock-order-028",
    date: daysAgo(48),
    tableNumber: 1,
    total: 78,
    items: ["Τσιπούρα", "Μπακλαβάς"],
  },
  {
    id: "cv-029",
    customerId: "cust-03",
    orderId: "mock-order-029",
    date: daysAgo(60),
    tableNumber: 2,
    total: 70,
    items: ["Γαρίδες Τηγανητές", "Cheesecake"],
  },

  // Ελένη Γεωργίου (cust-04) — 30 visits, ~€3,200 total (top spender)
  {
    id: "cv-030",
    customerId: "cust-04",
    orderId: "mock-order-030",
    date: daysAgo(1),
    tableNumber: 11,
    total: 125,
    items: [
      "Αστακομακαρονάδα",
      "Χτένια Ωμά",
      "Καρπάτσιο Λαβρακιού",
      "Μπακλαβάς",
    ],
  },
  {
    id: "cv-031",
    customerId: "cust-04",
    orderId: "mock-order-031",
    date: daysAgo(4),
    tableNumber: 12,
    total: 118,
    items: ["Φαγκρί", "Ταρτάρ Γαρίδας", "Τιραμισού"],
  },
  {
    id: "cv-032",
    customerId: "cust-04",
    orderId: "mock-order-032",
    date: daysAgo(7),
    tableNumber: 11,
    total: 105,
    items: ["Γαρίδες Θερμαϊκού", "Καβουροσαλάτα"],
  },
  {
    id: "cv-033",
    customerId: "cust-04",
    orderId: "mock-order-033",
    date: daysAgo(10),
    tableNumber: 12,
    total: 98,
    items: ["Συναγρίδα", "Σαγανάκι Γαρίδες", "Cheesecake"],
  },
  {
    id: "cv-034",
    customerId: "cust-04",
    orderId: "mock-order-034",
    date: daysAgo(14),
    tableNumber: 11,
    total: 112,
    items: ["Αστακομακαρονάδα", "Μπαρμπούνι"],
  },
  {
    id: "cv-035",
    customerId: "cust-04",
    orderId: "mock-order-035",
    date: daysAgo(18),
    tableNumber: 7,
    total: 95,
    items: ["Τσιπούρα", "Ταραμοσαλάτα Λευκή", "Lemon Bar"],
  },
  {
    id: "cv-036",
    customerId: "cust-04",
    orderId: "mock-order-036",
    date: daysAgo(22),
    tableNumber: 11,
    total: 108,
    items: ["Καρπάτσιο Λαβρακιού", "Φαγκρί", "Τιραμισού"],
  },
  {
    id: "cv-037",
    customerId: "cust-04",
    orderId: "mock-order-037",
    date: daysAgo(28),
    tableNumber: 12,
    total: 130,
    items: ["Ψαρόσουπα", "Χτένια Ωμά"],
  },
  {
    id: "cv-038",
    customerId: "cust-04",
    orderId: "mock-order-038",
    date: daysAgo(35),
    tableNumber: 11,
    total: 88,
    items: ["Γαριδομακαρονάδα", "Καλαμαράκια Τηγανητά"],
  },
  {
    id: "cv-039",
    customerId: "cust-04",
    orderId: "mock-order-039",
    date: daysAgo(42),
    tableNumber: 9,
    total: 115,
    items: ["Γαρίδες Θερμαϊκού", "Ταρτάρ Γαρίδας", "Μπακλαβάς"],
  },
  {
    id: "cv-040",
    customerId: "cust-04",
    orderId: "mock-order-040",
    date: daysAgo(50),
    tableNumber: 11,
    total: 102,
    items: ["Αστακομακαρονάδα", "Μελιτζανοσαλάτα"],
  },
  {
    id: "cv-041",
    customerId: "cust-04",
    orderId: "mock-order-041",
    date: daysAgo(58),
    tableNumber: 12,
    total: 96,
    items: ["Καλαμάρι", "Σαγανάκι Γαρίδες"],
  },
  {
    id: "cv-042",
    customerId: "cust-04",
    orderId: "mock-order-042",
    date: daysAgo(65),
    tableNumber: 11,
    total: 110,
    items: ["Φαγκρί", "Καβουροσαλάτα", "Cheesecake"],
  },

  // Δημήτρης Αλεξίου (cust-05) — 8 visits, ~€520 total
  {
    id: "cv-043",
    customerId: "cust-05",
    orderId: "mock-order-043",
    date: daysAgo(6),
    tableNumber: 2,
    total: 68,
    items: ["Γαριδομακαρονάδα", "Μελιτζανοσαλάτα"],
  },
  {
    id: "cv-044",
    customerId: "cust-05",
    orderId: "mock-order-044",
    date: daysAgo(18),
    tableNumber: 1,
    total: 72,
    items: ["Καλαμαράκια Τηγανητά", "Ταραμοσαλάτα Λευκή"],
  },
  {
    id: "cv-045",
    customerId: "cust-05",
    orderId: "mock-order-045",
    date: daysAgo(32),
    tableNumber: 8,
    total: 58,
    items: ["Χταπόδι", "Lemon Bar"],
  },
  {
    id: "cv-046",
    customerId: "cust-05",
    orderId: "mock-order-046",
    date: daysAgo(50),
    tableNumber: 2,
    total: 65,
    items: ["Αχνιστά Όστρακα", "Τιραμισού"],
  },
  {
    id: "cv-047",
    customerId: "cust-05",
    orderId: "mock-order-047",
    date: daysAgo(68),
    tableNumber: 1,
    total: 82,
    items: ["Τσιπούρα", "Cheesecake"],
  },

  // Σοφία Νικολάου (cust-06) — 15 visits, ~€1,100 total
  {
    id: "cv-048",
    customerId: "cust-06",
    orderId: "mock-order-048",
    date: daysAgo(3),
    tableNumber: 5,
    total: 75,
    items: ["Γαριδομακαρονάδα", "Ταραμοσαλάτα Λευκή", "Τιραμισού"],
  },
  {
    id: "cv-049",
    customerId: "cust-06",
    orderId: "mock-order-049",
    date: daysAgo(10),
    tableNumber: 4,
    total: 68,
    items: ["Αστακομακαρονάδα"],
  },
  {
    id: "cv-050",
    customerId: "cust-06",
    orderId: "mock-order-050",
    date: daysAgo(17),
    tableNumber: 5,
    total: 82,
    items: ["Καλαμαράκια Τηγανητά", "Μελιτζανοσαλάτα", "Μπακλαβάς"],
  },
  {
    id: "cv-051",
    customerId: "cust-06",
    orderId: "mock-order-051",
    date: daysAgo(25),
    tableNumber: 6,
    total: 72,
    items: ["Γαριδομακαρονάδα", "Lemon Bar"],
  },
  {
    id: "cv-052",
    customerId: "cust-06",
    orderId: "mock-order-052",
    date: daysAgo(38),
    tableNumber: 5,
    total: 78,
    items: ["Αστακομακαρονάδα", "Cheesecake"],
  },
  {
    id: "cv-053",
    customerId: "cust-06",
    orderId: "mock-order-053",
    date: daysAgo(52),
    tableNumber: 4,
    total: 65,
    items: ["Γαρίδες Τηγανητές", "Τιραμισού"],
  },
  {
    id: "cv-054",
    customerId: "cust-06",
    orderId: "mock-order-054",
    date: daysAgo(66),
    tableNumber: 5,
    total: 70,
    items: ["Γαριδομακαρονάδα", "Μελιτζανοσαλάτα"],
  },

  // Κώστας Παπανικολάου (cust-07) — 5 visits, ~€380 total
  {
    id: "cv-055",
    customerId: "cust-07",
    orderId: "mock-order-055",
    date: daysAgo(5),
    tableNumber: 1,
    total: 78,
    items: ["Τσιπούρα", "Ταραμοσαλάτα Λευκή"],
  },
  {
    id: "cv-056",
    customerId: "cust-07",
    orderId: "mock-order-056",
    date: daysAgo(12),
    tableNumber: 2,
    total: 72,
    items: ["Καλαμαράκια Τηγανητά", "Γαριδομακαρονάδα"],
  },
  {
    id: "cv-057",
    customerId: "cust-07",
    orderId: "mock-order-057",
    date: daysAgo(20),
    tableNumber: 8,
    total: 85,
    items: ["Φαγκρί", "Μπακλαβάς"],
  },
  {
    id: "cv-058",
    customerId: "cust-07",
    orderId: "mock-order-058",
    date: daysAgo(26),
    tableNumber: 1,
    total: 68,
    items: ["Σαγανάκι Γαρίδες", "Cheesecake"],
  },

  // Αναστασία Βασιλείου (cust-08) — 22 visits, ~€1,800 total
  {
    id: "cv-059",
    customerId: "cust-08",
    orderId: "mock-order-059",
    date: daysAgo(2),
    tableNumber: 6,
    total: 92,
    items: ["Αστακομακαρονάδα", "Καβουροσαλάτα", "Τιραμισού"],
  },
  {
    id: "cv-060",
    customerId: "cust-08",
    orderId: "mock-order-060",
    date: daysAgo(6),
    tableNumber: 12,
    total: 85,
    items: ["Γαρίδες Θερμαϊκού", "Ταραμοσαλάτα Λευκή"],
  },
  {
    id: "cv-061",
    customerId: "cust-08",
    orderId: "mock-order-061",
    date: daysAgo(11),
    tableNumber: 6,
    total: 78,
    items: ["Τσιπούρα", "Σαγανάκι Γαρίδες"],
  },
  {
    id: "cv-062",
    customerId: "cust-08",
    orderId: "mock-order-062",
    date: daysAgo(17),
    tableNumber: 11,
    total: 95,
    items: ["Φαγκρί", "Χτένια Ωμά", "Μπακλαβάς"],
  },
  {
    id: "cv-063",
    customerId: "cust-08",
    orderId: "mock-order-063",
    date: daysAgo(24),
    tableNumber: 6,
    total: 82,
    items: ["Αστακομακαρονάδα", "Lemon Bar"],
  },
  {
    id: "cv-064",
    customerId: "cust-08",
    orderId: "mock-order-064",
    date: daysAgo(32),
    tableNumber: 12,
    total: 75,
    items: ["Μπαρμπούνι", "Μελιτζανοσαλάτα"],
  },
  {
    id: "cv-065",
    customerId: "cust-08",
    orderId: "mock-order-065",
    date: daysAgo(40),
    tableNumber: 6,
    total: 88,
    items: ["Γαρίδες Θερμαϊκού", "Ταρτάρ Γαρίδας"],
  },
  {
    id: "cv-066",
    customerId: "cust-08",
    orderId: "mock-order-066",
    date: daysAgo(50),
    tableNumber: 11,
    total: 72,
    items: ["Καλαμαράκια Τηγανητά", "Cheesecake"],
  },
  {
    id: "cv-067",
    customerId: "cust-08",
    orderId: "mock-order-067",
    date: daysAgo(60),
    tableNumber: 6,
    total: 98,
    items: ["Συναγρίδα", "Σαγανάκι Γαρίδες", "Τιραμισού"],
  },
  {
    id: "cv-068",
    customerId: "cust-08",
    orderId: "mock-order-068",
    date: daysAgo(70),
    tableNumber: 12,
    total: 68,
    items: ["Γαριδομακαρονάδα", "Ταραμοσαλάτα Λευκή"],
  },

  // Πέτρος Ιωάννου (cust-09) — 3 visits, ~€240 total, idle 45 days
  {
    id: "cv-069",
    customerId: "cust-09",
    orderId: "mock-order-069",
    date: daysAgo(45),
    tableNumber: 3,
    total: 82,
    items: ["Τσιπούρα", "Μελιτζανοσαλάτα", "Τιραμισού"],
  },
  {
    id: "cv-070",
    customerId: "cust-09",
    orderId: "mock-order-070",
    date: daysAgo(65),
    tableNumber: 4,
    total: 78,
    items: ["Γαριδομακαρονάδα", "Cheesecake"],
  },
  {
    id: "cv-071",
    customerId: "cust-09",
    orderId: "mock-order-071",
    date: daysAgo(85),
    tableNumber: 3,
    total: 80,
    items: ["Σαγανάκι Γαρίδες", "Καλαμαράκια Τηγανητά"],
  },

  // Χριστίνα Μιχαήλ (cust-10) — 2 visits, ~€180 total, idle 60 days
  {
    id: "cv-072",
    customerId: "cust-10",
    orderId: "mock-order-072",
    date: daysAgo(60),
    tableNumber: 9,
    total: 95,
    items: ["Φαγκρί", "Ταραμοσαλάτα Λευκή", "Μπακλαβάς"],
  },
  {
    id: "cv-073",
    customerId: "cust-10",
    orderId: "mock-order-073",
    date: daysAgo(80),
    tableNumber: 10,
    total: 85,
    items: ["Αστακομακαρονάδα", "Lemon Bar"],
  },

  // Αλέξανδρος Θεοδώρου (cust-11) — 10 visits, ~€720 total
  {
    id: "cv-074",
    customerId: "cust-11",
    orderId: "mock-order-074",
    date: daysAgo(5),
    tableNumber: 3,
    total: 78,
    items: ["Γαριδομακαρονάδα", "Καβουροσαλάτα"],
  },
  {
    id: "cv-075",
    customerId: "cust-11",
    orderId: "mock-order-075",
    date: daysAgo(14),
    tableNumber: 4,
    total: 72,
    items: ["Τσιπούρα", "Μελιτζανοσαλάτα"],
  },
  {
    id: "cv-076",
    customerId: "cust-11",
    orderId: "mock-order-076",
    date: daysAgo(25),
    tableNumber: 3,
    total: 65,
    items: ["Καλαμαράκια Τηγανητά", "Τιραμισού"],
  },
  {
    id: "cv-077",
    customerId: "cust-11",
    orderId: "mock-order-077",
    date: daysAgo(40),
    tableNumber: 5,
    total: 82,
    items: ["Φαγκρί", "Ταραμοσαλάτα Λευκή"],
  },
  {
    id: "cv-078",
    customerId: "cust-11",
    orderId: "mock-order-078",
    date: daysAgo(55),
    tableNumber: 3,
    total: 70,
    items: ["Αστακομακαρονάδα", "Cheesecake"],
  },

  // Κατερίνα Σταματίου (cust-12) — 7 visits, ~€490 total
  {
    id: "cv-079",
    customerId: "cust-12",
    orderId: "mock-order-079",
    date: daysAgo(7),
    tableNumber: 2,
    total: 72,
    items: ["Καρπάτσιο Λαβρακιού", "Σαγανάκι Γαρίδες"],
  },
  {
    id: "cv-080",
    customerId: "cust-12",
    orderId: "mock-order-080",
    date: daysAgo(18),
    tableNumber: 1,
    total: 68,
    items: ["Γαριδομακαρονάδα", "Μελιτζανοσαλάτα"],
  },
  {
    id: "cv-081",
    customerId: "cust-12",
    orderId: "mock-order-081",
    date: daysAgo(30),
    tableNumber: 8,
    total: 75,
    items: ["Τσιπούρα", "Lemon Bar"],
  },
  {
    id: "cv-082",
    customerId: "cust-12",
    orderId: "mock-order-082",
    date: daysAgo(48),
    tableNumber: 2,
    total: 62,
    items: ["Χταπόδι", "Τιραμισού"],
  },

  // Θανάσης Πολυχρόνου (cust-13) — 1 visit, €85 total, idle 90 days
  {
    id: "cv-083",
    customerId: "cust-13",
    orderId: "mock-order-083",
    date: daysAgo(90),
    tableNumber: 10,
    total: 85,
    items: ["Μπαρμπούνι", "Ταραμοσαλάτα Λευκή", "Μπακλαβάς"],
  },

  // Βασιλική Οικονόμου (cust-14) — 14 visits, ~€960 total, 8/10 stamps
  {
    id: "cv-084",
    customerId: "cust-14",
    orderId: "mock-order-084",
    date: daysAgo(3),
    tableNumber: 4,
    total: 72,
    items: ["Γαριδομακαρονάδα", "Ταραμοσαλάτα Λευκή"],
  },
  {
    id: "cv-085",
    customerId: "cust-14",
    orderId: "mock-order-085",
    date: daysAgo(10),
    tableNumber: 5,
    total: 68,
    items: ["Καλαμαράκια Τηγανητά", "Μελιτζανοσαλάτα"],
  },
  {
    id: "cv-086",
    customerId: "cust-14",
    orderId: "mock-order-086",
    date: daysAgo(18),
    tableNumber: 4,
    total: 78,
    items: ["Τσιπούρα", "Lemon Bar"],
  },
  {
    id: "cv-087",
    customerId: "cust-14",
    orderId: "mock-order-087",
    date: daysAgo(28),
    tableNumber: 6,
    total: 65,
    items: ["Σαγανάκι Γαρίδες", "Cheesecake"],
  },
  {
    id: "cv-088",
    customerId: "cust-14",
    orderId: "mock-order-088",
    date: daysAgo(40),
    tableNumber: 4,
    total: 72,
    items: ["Αστακομακαρονάδα", "Τιραμισού"],
  },
  {
    id: "cv-089",
    customerId: "cust-14",
    orderId: "mock-order-089",
    date: daysAgo(55),
    tableNumber: 5,
    total: 68,
    items: ["Γαρίδες Τηγανητές", "Μπακλαβάς"],
  },

  // Γεώργιος Αθανασίου (cust-15) — 9 visits, ~€650 total, 85 points
  {
    id: "cv-090",
    customerId: "cust-15",
    orderId: "mock-order-090",
    date: daysAgo(4),
    tableNumber: 9,
    total: 75,
    items: ["Γαριδομακαρονάδα", "Καβουροσαλάτα"],
  },
  {
    id: "cv-091",
    customerId: "cust-15",
    orderId: "mock-order-091",
    date: daysAgo(12),
    tableNumber: 10,
    total: 72,
    items: ["Τσιπούρα", "Ταραμοσαλάτα Λευκή"],
  },
  {
    id: "cv-092",
    customerId: "cust-15",
    orderId: "mock-order-092",
    date: daysAgo(22),
    tableNumber: 9,
    total: 68,
    items: ["Σαγανάκι Γαρίδες", "Μελιτζανοσαλάτα"],
  },
  {
    id: "cv-093",
    customerId: "cust-15",
    orderId: "mock-order-093",
    date: daysAgo(35),
    tableNumber: 7,
    total: 82,
    items: ["Φαγκρί", "Cheesecake"],
  },
  {
    id: "cv-094",
    customerId: "cust-15",
    orderId: "mock-order-094",
    date: daysAgo(50),
    tableNumber: 9,
    total: 70,
    items: ["Αστακομακαρονάδα", "Lemon Bar"],
  },
];

export const initialLoyaltySettings: LoyaltySettings = {
  pointsPerEuro: 1,
  pointsForReward: 100,
  rewardValue: 5,
  stampsForFreeItem: 10,
};

// === Staff Mock Data ===

export const initialStaff: StaffMember[] = [
  {
    id: "staff1",
    name: "Αλέξανδρος Κ.",
    role: "manager",
    pin: "1234",
    phone: "6971234567",
    email: "alex@blacksea.gr",
    isActive: true,
  },
  {
    id: "staff2",
    name: "Μαρίνα Π.",
    role: "waiter",
    pin: "5678",
    phone: "6972345678",
    isActive: true,
  },
  {
    id: "staff3",
    name: "Θοδωρής Μ.",
    role: "waiter",
    pin: "9012",
    phone: "6973456789",
    isActive: true,
  },
  {
    id: "staff4",
    name: "Ελισάβετ Δ.",
    role: "barman",
    pin: "3456",
    phone: "6974567890",
    isActive: true,
  },
  {
    id: "staff5",
    name: "Στέφανος Ν.",
    role: "chef",
    pin: "7890",
    phone: "6975678901",
    isActive: true,
  },
  {
    id: "staff6",
    name: "Κατερίνα Α.",
    role: "waiter",
    pin: "2345",
    phone: "6976789012",
    isActive: false,
  },
];

function generateCurrentWeekShifts(): Shift[] {
  const today = new Date();
  const dayOfWeek = today.getDay();
  // Monday = 0 offset. getDay() returns 0 for Sunday, 1 for Monday, etc.
  const mondayOffset = dayOfWeek === 0 ? -6 : 1 - dayOfWeek;
  const monday = new Date(today);
  monday.setDate(today.getDate() + mondayOffset);

  const shifts: Shift[] = [];
  const weekDates: string[] = [];

  for (let i = 0; i < 7; i++) {
    const d = new Date(monday);
    d.setDate(monday.getDate() + i);
    weekDates.push(d.toISOString().split("T")[0]);
  }

  // Manager (staff1): always morning
  for (let i = 0; i < 7; i++) {
    const type = i === 6 ? "off" : "morning"; // Sunday off
    shifts.push({
      id: `shift-s1-${i}`,
      staffId: "staff1",
      date: weekDates[i],
      type: type as Shift["type"],
    });
  }

  // Waiter Marina (staff2): mixed shifts
  const marinaPattern: Shift["type"][] = [
    "morning",
    "morning",
    "afternoon",
    "morning",
    "afternoon",
    "morning",
    "off",
  ];
  for (let i = 0; i < 7; i++) {
    shifts.push({
      id: `shift-s2-${i}`,
      staffId: "staff2",
      date: weekDates[i],
      type: marinaPattern[i],
    });
  }

  // Waiter Thodoris (staff3): mixed shifts
  const thodorisPattern: Shift["type"][] = [
    "afternoon",
    "morning",
    "morning",
    "afternoon",
    "morning",
    "off",
    "afternoon",
  ];
  for (let i = 0; i < 7; i++) {
    shifts.push({
      id: `shift-s3-${i}`,
      staffId: "staff3",
      date: weekDates[i],
      type: thodorisPattern[i],
    });
  }

  // Barman Elisavet (staff4): afternoon shifts
  const elisavetPattern: Shift["type"][] = [
    "afternoon",
    "afternoon",
    "afternoon",
    "off",
    "afternoon",
    "afternoon",
    "afternoon",
  ];
  for (let i = 0; i < 7; i++) {
    shifts.push({
      id: `shift-s4-${i}`,
      staffId: "staff4",
      date: weekDates[i],
      type: elisavetPattern[i],
    });
  }

  // Chef Stefanos (staff5): alternating morning/afternoon
  const stefanosPattern: Shift["type"][] = [
    "morning",
    "afternoon",
    "morning",
    "afternoon",
    "morning",
    "morning",
    "off",
  ];
  for (let i = 0; i < 7; i++) {
    shifts.push({
      id: `shift-s5-${i}`,
      staffId: "staff5",
      date: weekDates[i],
      type: stefanosPattern[i],
    });
  }

  return shifts;
}

export const initialShifts: Shift[] = generateCurrentWeekShifts();

export const initialChecklist: ChecklistItem[] = [
  // Opening
  {
    id: "cl-o1",
    type: "opening",
    label: "Έλεγχος καθαριότητας χώρου",
    checked: false,
  },
  {
    id: "cl-o2",
    type: "opening",
    label: "Ενεργοποίηση POS συστήματος",
    checked: false,
  },
  {
    id: "cl-o3",
    type: "opening",
    label: "Έλεγχος αποθήκης / πρώτων υλών",
    checked: false,
  },
  {
    id: "cl-o4",
    type: "opening",
    label: "Προετοιμασία τραπεζιών",
    checked: false,
  },
  {
    id: "cl-o5",
    type: "opening",
    label: "Έλεγχος εξοπλισμού κουζίνας",
    checked: false,
  },
  {
    id: "cl-o6",
    type: "opening",
    label: "Ενημέρωση μενού (εξαντλημένα)",
    checked: false,
  },
  // Closing
  {
    id: "cl-c1",
    type: "closing",
    label: "Κλείσιμο ταμείου / μέτρηση",
    checked: false,
  },
  {
    id: "cl-c2",
    type: "closing",
    label: "Καθαρισμός κουζίνας",
    checked: false,
  },
  {
    id: "cl-c3",
    type: "closing",
    label: "Καθαρισμός τραπεζιών & αίθουσας",
    checked: false,
  },
  { id: "cl-c4", type: "closing", label: "Έλεγχος αποθήκης", checked: false },
  {
    id: "cl-c5",
    type: "closing",
    label: "Κλείδωμα πορτών & παραθύρων",
    checked: false,
  },
  {
    id: "cl-c6",
    type: "closing",
    label: "Απενεργοποίηση εξοπλισμού",
    checked: false,
  },
];

export const initialStaffPerformance: StaffPerformance[] = [
  {
    staffId: "staff1",
    tablesServed: 8,
    revenue: 1200,
    avgServiceTime: 10,
    tips: 45,
  },
  {
    staffId: "staff2",
    tablesServed: 22,
    revenue: 2400,
    avgServiceTime: 8,
    tips: 120,
  },
  {
    staffId: "staff3",
    tablesServed: 18,
    revenue: 1800,
    avgServiceTime: 12,
    tips: 85,
  },
  {
    staffId: "staff4",
    tablesServed: 0,
    revenue: 950,
    avgServiceTime: 5,
    tips: 60,
  },
  {
    staffId: "staff5",
    tablesServed: 0,
    revenue: 0,
    avgServiceTime: 0,
    tips: 0,
  },
];

// Helper function to generate unique IDs
export function generateId(): string {
  return Math.random().toString(36).substring(2, 11);
}

// Helper to format price in Greek format
export function formatPrice(price: number): string {
  return new Intl.NumberFormat("el-GR", {
    style: "currency",
    currency: "EUR",
  }).format(price);
}

// Helper to format date/time in Greek
export function formatDateTime(dateString: string): string {
  return new Intl.DateTimeFormat("el-GR", {
    hour: "2-digit",
    minute: "2-digit",
    day: "2-digit",
    month: "2-digit",
  }).format(new Date(dateString));
}

export function formatTime(dateString: string): string {
  return new Intl.DateTimeFormat("el-GR", {
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(dateString));
}
