// EatFlow POS - Mock Data for Greek Restaurant

import type { Table, Category, Product, Order, Zone, Modifier } from "./types";

export const initialZones: Zone[] = [
  { id: "zone1", name: "Εσωτερικό", color: "#3b82f6", order: 1 },
  { id: "zone2", name: "Βεράντα", color: "#22c55e", order: 2 },
  { id: "zone3", name: "Μπαρ", color: "#f59e0b", order: 3 },
];

export const initialTables: Table[] = [
  // Zone 1 - Εσωτερικό
  {
    id: "t1",
    number: 1,
    capacity: 2,
    status: "available",
    zoneId: "zone1",
    x: 80,
    y: 80,
    shape: "round",
    rotation: 0,
  },
  {
    id: "t2",
    number: 2,
    capacity: 2,
    status: "available",
    zoneId: "zone1",
    x: 200,
    y: 80,
    shape: "round",
    rotation: 0,
  },
  {
    id: "t3",
    number: 3,
    capacity: 4,
    status: "available",
    zoneId: "zone1",
    x: 80,
    y: 200,
    shape: "square",
    rotation: 0,
  },
  {
    id: "t4",
    number: 4,
    capacity: 4,
    status: "available",
    zoneId: "zone1",
    x: 200,
    y: 200,
    shape: "square",
    rotation: 0,
  },
  {
    id: "t5",
    number: 5,
    capacity: 4,
    status: "available",
    zoneId: "zone1",
    x: 320,
    y: 80,
    shape: "square",
    rotation: 0,
  },
  {
    id: "t6",
    number: 6,
    capacity: 6,
    status: "available",
    zoneId: "zone1",
    x: 320,
    y: 200,
    shape: "rectangle",
    rotation: 0,
  },
  // Zone 2 - Βεράντα
  {
    id: "t7",
    number: 7,
    capacity: 6,
    status: "available",
    zoneId: "zone2",
    x: 80,
    y: 80,
    shape: "rectangle",
    rotation: 0,
  },
  {
    id: "t8",
    number: 8,
    capacity: 2,
    status: "available",
    zoneId: "zone2",
    x: 280,
    y: 80,
    shape: "round",
    rotation: 0,
  },
  {
    id: "t9",
    number: 9,
    capacity: 4,
    status: "available",
    zoneId: "zone2",
    x: 80,
    y: 220,
    shape: "square",
    rotation: 0,
  },
  {
    id: "t10",
    number: 10,
    capacity: 4,
    status: "available",
    zoneId: "zone2",
    x: 280,
    y: 220,
    shape: "square",
    rotation: 0,
  },
  // Zone 3 - Μπαρ
  {
    id: "t11",
    number: 11,
    capacity: 6,
    status: "available",
    zoneId: "zone3",
    x: 80,
    y: 80,
    shape: "rectangle",
    rotation: 0,
  },
  {
    id: "t12",
    number: 12,
    capacity: 8,
    status: "available",
    zoneId: "zone3",
    x: 80,
    y: 220,
    shape: "rectangle",
    rotation: 0,
  },
];

export const initialCategories: Category[] = [
  { id: "cat1", name: "Ορεκτικά", order: 1 },
  { id: "cat2", name: "Σαλάτες", order: 2 },
  { id: "cat3", name: "Κυρίως Πιάτα", order: 3 },
  { id: "cat4", name: "Θαλασσινά", order: 4 },
  { id: "cat5", name: "Ποτά", order: 5 },
  { id: "cat6", name: "Κρασιά", order: 6 },
  { id: "cat7", name: "Επιδόρπια", order: 7 },
];

export const initialModifiers: Modifier[] = [
  {
    id: "mod1",
    name: "Χωρίς κρεμμύδι",
    price: 0,
    categoryIds: ["cat1", "cat2", "cat3"],
  },
  {
    id: "mod2",
    name: "Χωρίς σάλτσα",
    price: 0,
    categoryIds: ["cat1", "cat2", "cat3", "cat4"],
  },
  { id: "mod3", name: "Extra τυρί", price: 1.5, categoryIds: ["cat1", "cat3"] },
  { id: "mod4", name: "Extra μπέικον", price: 2.0, categoryIds: ["cat3"] },
  { id: "mod5", name: "Well done", price: 0, categoryIds: ["cat3"] },
  { id: "mod6", name: "Medium", price: 0, categoryIds: ["cat3"] },
  { id: "mod7", name: "Rare", price: 0, categoryIds: ["cat3"] },
  {
    id: "mod8",
    name: "Χωρίς γλουτένη",
    price: 0,
    categoryIds: ["cat1", "cat2", "cat3", "cat4"],
  },
  {
    id: "mod9",
    name: "Χωρίς λακτόζη",
    price: 0,
    categoryIds: ["cat1", "cat2", "cat3", "cat4", "cat7"],
  },
  { id: "mod10", name: "Χωρίς πάγο", price: 0, categoryIds: ["cat5"] },
  { id: "mod11", name: "Extra σιρόπι", price: 0.5, categoryIds: ["cat7"] },
];

export const initialProducts: Product[] = [
  // Ορεκτικά (Appetizers) - cold unless heated
  {
    id: "p1",
    name: "Τζατζίκι",
    price: 4.5,
    categoryId: "cat1",
    description: "Παραδοσιακό τζατζίκι με σκόρδο",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p2",
    name: "Ταραμοσαλάτα",
    price: 5.0,
    categoryId: "cat1",
    description: "Σπιτική ταραμοσαλάτα",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p3",
    name: "Μελιτζανοσαλάτα",
    price: 5.0,
    categoryId: "cat1",
    description: "Καπνιστή μελιτζάνα",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p4",
    name: "Φέτα Ψητή",
    price: 6.5,
    categoryId: "cat1",
    description: "Φέτα στο φούρνο με πιπεριά και ντομάτα",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p5",
    name: "Σαγανάκι",
    price: 7.0,
    categoryId: "cat1",
    description: "Τηγανητό τυρί κεφαλογραβιέρα",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p6",
    name: "Κολοκυθοκεφτέδες",
    price: 6.0,
    categoryId: "cat1",
    description: "Σπιτικοί κολοκυθοκεφτέδες",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },

  // Σαλάτες (Salads) - cold
  {
    id: "p7",
    name: "Χωριάτικη",
    price: 8.0,
    categoryId: "cat2",
    description: "Ντομάτα, αγγούρι, πιπεριά, κρεμμύδι, ελιές, φέτα",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p8",
    name: "Σαλάτα του Σεφ",
    price: 9.5,
    categoryId: "cat2",
    description: "Μαρούλι, ρόκα, ντοματίνια, παρμεζάνα",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p9",
    name: "Σαλάτα Κρητική",
    price: 8.5,
    categoryId: "cat2",
    description: "Παξιμάδι, ντομάτα, ξυνομυζήθρα",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },

  // Κυρίως Πιάτα (Main Courses) - hot
  {
    id: "p10",
    name: "Μουσακάς",
    price: 12.0,
    categoryId: "cat3",
    description: "Παραδοσιακός μουσακάς",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p11",
    name: "Παστίτσιο",
    price: 11.0,
    categoryId: "cat3",
    description: "Κλασικό παστίτσιο με κιμά",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p12",
    name: "Σουβλάκι Χοιρινό",
    price: 10.0,
    categoryId: "cat3",
    description: "Δύο καλαμάκια με πίτα και πατάτες",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p13",
    name: "Μπιφτέκι",
    price: 11.5,
    categoryId: "cat3",
    description: "Χειροποίητο μπιφτέκι με φέτα",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p14",
    name: "Κοτόπουλο Σχάρας",
    price: 10.5,
    categoryId: "cat3",
    description: "Φιλέτο κοτόπουλο με λαχανικά",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p15",
    name: "Αρνίσια Παϊδάκια",
    price: 16.0,
    categoryId: "cat3",
    description: "Παϊδάκια στα κάρβουνα",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },

  // Θαλασσινά (Seafood) - hot
  {
    id: "p16",
    name: "Καλαμαράκια Τηγανητά",
    price: 12.0,
    categoryId: "cat4",
    description: "Τραγανά καλαμαράκια",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p17",
    name: "Γαρίδες Σαγανάκι",
    price: 14.0,
    categoryId: "cat4",
    description: "Γαρίδες με σάλτσα φέτας",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p18",
    name: "Τσιπούρα Σχάρας",
    price: 18.0,
    categoryId: "cat4",
    description: "Φρέσκια τσιπούρα",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },

  // Ποτά (Drinks) - bar
  {
    id: "p19",
    name: "Νερό 500ml",
    price: 1.0,
    categoryId: "cat5",
    vatRate: 24,
    available: true,
    station: "bar",
    modifierIds: [],
  },
  {
    id: "p20",
    name: "Νερό 1L",
    price: 1.5,
    categoryId: "cat5",
    vatRate: 24,
    available: true,
    station: "bar",
    modifierIds: [],
  },
  {
    id: "p21",
    name: "Coca-Cola",
    price: 2.5,
    categoryId: "cat5",
    vatRate: 24,
    available: true,
    station: "bar",
    modifierIds: [],
  },
  {
    id: "p22",
    name: "Πορτοκαλάδα",
    price: 2.5,
    categoryId: "cat5",
    vatRate: 24,
    available: true,
    station: "bar",
    modifierIds: [],
  },
  {
    id: "p23",
    name: "Μπύρα Μύθος",
    price: 4.0,
    categoryId: "cat5",
    vatRate: 24,
    available: true,
    station: "bar",
    modifierIds: [],
  },
  {
    id: "p24",
    name: "Μπύρα Fix",
    price: 4.0,
    categoryId: "cat5",
    vatRate: 24,
    available: true,
    station: "bar",
    modifierIds: [],
  },
  {
    id: "p25",
    name: "Ούζο 200ml",
    price: 8.0,
    categoryId: "cat5",
    vatRate: 24,
    available: true,
    station: "bar",
    modifierIds: [],
  },
  {
    id: "p26",
    name: "Τσίπουρο",
    price: 6.0,
    categoryId: "cat5",
    vatRate: 24,
    available: true,
    station: "bar",
    modifierIds: [],
  },

  // Κρασιά (Wines) - bar
  {
    id: "p27",
    name: "Κρασί Λευκό (500ml)",
    price: 8.0,
    categoryId: "cat6",
    description: "Χύμα λευκό κρασί",
    vatRate: 24,
    available: true,
    station: "bar",
    modifierIds: [],
  },
  {
    id: "p28",
    name: "Κρασί Κόκκινο (500ml)",
    price: 8.0,
    categoryId: "cat6",
    description: "Χύμα κόκκινο κρασί",
    vatRate: 24,
    available: true,
    station: "bar",
    modifierIds: [],
  },
  {
    id: "p29",
    name: "Κρασί Ροζέ (500ml)",
    price: 8.5,
    categoryId: "cat6",
    description: "Χύμα ροζέ κρασί",
    vatRate: 24,
    available: true,
    station: "bar",
    modifierIds: [],
  },

  // Επιδόρπια (Desserts) - dessert
  {
    id: "p30",
    name: "Γαλακτομπούρεκο",
    price: 5.0,
    categoryId: "cat7",
    description: "Σπιτικό γαλακτομπούρεκο",
    vatRate: 13,
    available: true,
    station: "dessert",
    modifierIds: [],
  },
  {
    id: "p31",
    name: "Μπακλαβάς",
    price: 5.0,
    categoryId: "cat7",
    description: "Παραδοσιακός μπακλαβάς",
    vatRate: 13,
    available: true,
    station: "dessert",
    modifierIds: [],
  },
  {
    id: "p32",
    name: "Παγωτό",
    price: 4.5,
    categoryId: "cat7",
    description: "Δύο μπάλες της επιλογής σας",
    vatRate: 13,
    available: true,
    station: "dessert",
    modifierIds: [],
  },
  {
    id: "p33",
    name: "Φρέσκα Φρούτα",
    price: 6.0,
    categoryId: "cat7",
    description: "Εποχιακά φρούτα",
    vatRate: 13,
    available: true,
    station: "dessert",
    modifierIds: [],
  },
];

export const initialOrders: Order[] = [];

// Helper function to generate unique IDs
export function generateId(): string {
  return Math.random().toString(36).substring(2, 11);
}

// Helper to format price in Greek format
export function formatPrice(price: number): string {
  return new Intl.NumberFormat("el-GR", {
    style: "currency",
    currency: "EUR",
  }).format(price);
}

// Helper to format date/time in Greek
export function formatDateTime(dateString: string): string {
  return new Intl.DateTimeFormat("el-GR", {
    hour: "2-digit",
    minute: "2-digit",
    day: "2-digit",
    month: "2-digit",
  }).format(new Date(dateString));
}

export function formatTime(dateString: string): string {
  return new Intl.DateTimeFormat("el-GR", {
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(dateString));
}
