// EatFlow POS - Mock Data for Μαύρη Θάλασσα (Black Sea) Restaurant

import type {
  Table,
  Category,
  Product,
  Order,
  Zone,
  Modifier,
  Ingredient,
  Recipe,
  WasteEntry,
  Supplier,
  SupplierOrder,
} from "./types";

export const initialZones: Zone[] = [
  { id: "zone1", name: "Εσωτερικό", color: "#3b82f6", order: 1 },
  { id: "zone2", name: "Βεράντα", color: "#22c55e", order: 2 },
  { id: "zone3", name: "Μπαρ", color: "#f59e0b", order: 3 },
];

export const initialTables: Table[] = [
  // Zone 1 - Εσωτερικό (left side of floor plan)
  {
    id: "t1",
    number: 1,
    capacity: 2,
    status: "available",
    zoneId: "zone1",
    x: 10,
    y: 15,
    shape: "round",
    rotation: 0,
  },
  {
    id: "t2",
    number: 2,
    capacity: 2,
    status: "available",
    zoneId: "zone1",
    x: 25,
    y: 15,
    shape: "round",
    rotation: 0,
  },
  {
    id: "t3",
    number: 3,
    capacity: 4,
    status: "available",
    zoneId: "zone1",
    x: 10,
    y: 45,
    shape: "square",
    rotation: 0,
  },
  {
    id: "t4",
    number: 4,
    capacity: 4,
    status: "available",
    zoneId: "zone1",
    x: 25,
    y: 45,
    shape: "square",
    rotation: 0,
  },
  {
    id: "t5",
    number: 5,
    capacity: 4,
    status: "available",
    zoneId: "zone1",
    x: 10,
    y: 75,
    shape: "square",
    rotation: 0,
  },
  {
    id: "t6",
    number: 6,
    capacity: 6,
    status: "available",
    zoneId: "zone1",
    x: 25,
    y: 75,
    shape: "rectangle",
    rotation: 0,
  },
  // Zone 2 - Βεράντα (right side of floor plan)
  {
    id: "t7",
    number: 7,
    capacity: 6,
    status: "available",
    zoneId: "zone2",
    x: 55,
    y: 15,
    shape: "rectangle",
    rotation: 0,
  },
  {
    id: "t8",
    number: 8,
    capacity: 2,
    status: "available",
    zoneId: "zone2",
    x: 75,
    y: 15,
    shape: "round",
    rotation: 0,
  },
  {
    id: "t9",
    number: 9,
    capacity: 4,
    status: "available",
    zoneId: "zone2",
    x: 55,
    y: 50,
    shape: "square",
    rotation: 0,
  },
  {
    id: "t10",
    number: 10,
    capacity: 4,
    status: "available",
    zoneId: "zone2",
    x: 75,
    y: 50,
    shape: "square",
    rotation: 0,
  },
  // Zone 3 - Μπαρ (bottom center)
  {
    id: "t11",
    number: 11,
    capacity: 6,
    status: "available",
    zoneId: "zone3",
    x: 55,
    y: 82,
    shape: "rectangle",
    rotation: 0,
  },
  {
    id: "t12",
    number: 12,
    capacity: 8,
    status: "available",
    zoneId: "zone3",
    x: 75,
    y: 82,
    shape: "rectangle",
    rotation: 0,
  },
];

export const initialCategories: Category[] = [
  { id: "cat1", name: "Ωμά", order: 1 },
  { id: "cat2", name: "Κρύα Ορεκτικά", order: 2 },
  { id: "cat3", name: "Ζεστά Ορεκτικά", order: 3 },
  { id: "cat4", name: "Ψητά Θαλασσινά", order: 4 },
  { id: "cat5", name: "Μαγειρευτά", order: 5 },
  { id: "cat6", name: "Ζυμαρικά", order: 6 },
  { id: "cat7", name: "Γλυκά", order: 7 },
];

export const initialModifiers: Modifier[] = [
  {
    id: "mod1",
    name: "Χωρίς κρεμμύδι",
    price: 0,
    categoryIds: ["cat2", "cat3", "cat5"],
  },
  {
    id: "mod2",
    name: "Χωρίς σάλτσα",
    price: 0,
    categoryIds: ["cat3", "cat4", "cat5", "cat6"],
  },
  {
    id: "mod3",
    name: "Extra λεμόνι",
    price: 0,
    categoryIds: ["cat1", "cat4"],
  },
  {
    id: "mod4",
    name: "Extra ελαιόλαδο",
    price: 0,
    categoryIds: ["cat1", "cat2", "cat4"],
  },
  {
    id: "mod5",
    name: "Well done",
    price: 0,
    categoryIds: ["cat4"],
  },
  {
    id: "mod6",
    name: "Medium",
    price: 0,
    categoryIds: ["cat4"],
  },
  {
    id: "mod7",
    name: "Χωρίς αλάτι",
    price: 0,
    categoryIds: ["cat1", "cat2", "cat3", "cat4", "cat5", "cat6"],
  },
  {
    id: "mod8",
    name: "Χωρίς γλουτένη",
    price: 0,
    categoryIds: ["cat3", "cat5", "cat6", "cat7"],
  },
  {
    id: "mod9",
    name: "Χωρίς λακτόζη",
    price: 0,
    categoryIds: ["cat2", "cat3", "cat5", "cat7"],
  },
  {
    id: "mod10",
    name: "Για μοίρασμα",
    price: 0,
    categoryIds: ["cat1", "cat2", "cat3", "cat7"],
  },
  {
    id: "mod11",
    name: "Extra σάλτσα",
    price: 1.5,
    categoryIds: ["cat6"],
  },
];

export const initialProducts: Product[] = [
  // Ωμά (cat1, cold)
  {
    id: "p1",
    name: "Καρπάτσιο Λαβρακιού",
    price: 16,
    categoryId: "cat1",
    description: "Φρέσκο φιλέτο λαβρακιού με ελαιόλαδο και λεμόνι",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p2",
    name: "Καρπάτσιο Μπαρμπουνιού",
    price: 18,
    categoryId: "cat1",
    description: "Φρέσκο μπαρμπούνι σε λεπτές φέτες",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p3",
    name: "Ταρτάρ Γαρίδας",
    price: 18,
    categoryId: "cat1",
    description: "Ωμή γαρίδα με αρωματικά",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  // Κρύα Ορεκτικά (cat2, cold)
  {
    id: "p4",
    name: "Ταραμοσαλάτα Λευκή",
    price: 12,
    categoryId: "cat2",
    description: "Σπιτική λευκή ταραμοσαλάτα",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p5",
    name: "Μελιτζανοσαλάτα",
    price: 8,
    categoryId: "cat2",
    description: "Καπνιστή μελιτζάνα με ελαιόλαδο",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p6",
    name: "Καβουροσαλάτα",
    price: 16,
    categoryId: "cat2",
    description: "Φρέσκο καβούρι σε σαλάτα",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  {
    id: "p7",
    name: "Χτένια Ωμά",
    price: 22,
    categoryId: "cat2",
    description: "Φρέσκα χτένια με λεμόνι",
    vatRate: 13,
    available: true,
    station: "cold",
    modifierIds: [],
  },
  // Ζεστά Ορεκτικά (cat3, hot)
  {
    id: "p8",
    name: "Σαγανάκι Γαρίδες",
    price: 18,
    categoryId: "cat3",
    description: "Γαρίδες σαγανάκι με φέτα και ντομάτα",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p9",
    name: "Αχνιστά Όστρακα",
    price: 16,
    categoryId: "cat3",
    description: "Όστρακα αχνιστά με κρασί",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p10",
    name: "Καλαμαράκια Τηγανητά",
    price: 14,
    categoryId: "cat3",
    description: "Τραγανά καλαμαράκια με λεμόνι",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p11",
    name: "Γαρίδες Τηγανητές",
    price: 18,
    categoryId: "cat3",
    description: "Τηγανητές γαρίδες με σάλτσα",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  // Ψητά Θαλασσινά (cat4, hot)
  {
    id: "p12",
    name: "Τσιπούρα",
    price: 75,
    categoryId: "cat4",
    description: "Φρέσκια τσιπούρα σχάρας (κιλό)",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p13",
    name: "Μπαρμπούνι",
    price: 85,
    categoryId: "cat4",
    description: "Φρέσκο μπαρμπούνι σχάρας (κιλό)",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p14",
    name: "Φαγκρί",
    price: 95,
    categoryId: "cat4",
    description: "Φρέσκο φαγκρί σχάρας (κιλό)",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p15",
    name: "Συναγρίδα",
    price: 95,
    categoryId: "cat4",
    description: "Φρέσκια συναγρίδα σχάρας (κιλό)",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p16",
    name: "Γαρίδες Θερμαϊκού",
    price: 95,
    categoryId: "cat4",
    description: "Φρέσκιες γαρίδες Θερμαϊκού σχάρας (κιλό)",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p17",
    name: "Καλαμάρι",
    price: 55,
    categoryId: "cat4",
    description: "Φρέσκο καλαμάρι σχάρας (κιλό)",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p18",
    name: "Χταπόδι",
    price: 48,
    categoryId: "cat4",
    description: "Χταπόδι σχάρας (κιλό)",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  // Μαγειρευτά (cat5, hot)
  {
    id: "p19",
    name: "Ψαρόσουπα",
    price: 90,
    categoryId: "cat5",
    description: "Παραδοσιακή ψαρόσουπα",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p20",
    name: "Φρικασέ",
    price: 120,
    categoryId: "cat5",
    description: "Φρικασέ θαλασσινών",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p21",
    name: "Κοκκινιστό",
    price: 120,
    categoryId: "cat5",
    description: "Θαλασσινά κοκκινιστά",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p22",
    name: "Πλακί",
    price: 140,
    categoryId: "cat5",
    description: "Ψάρι πλακί στο φούρνο",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  // Ζυμαρικά (cat6, hot)
  {
    id: "p23",
    name: "Γαριδομακαρονάδα",
    price: 28,
    categoryId: "cat6",
    description: "Λιγκουίνι με γαρίδες και σάλτσα ντομάτας",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  {
    id: "p24",
    name: "Αστακομακαρονάδα",
    price: 45,
    categoryId: "cat6",
    description: "Λιγκουίνι με αστακό",
    vatRate: 13,
    available: true,
    station: "hot",
    modifierIds: [],
  },
  // Γλυκά (cat7, dessert)
  {
    id: "p25",
    name: "Μπακλαβάς",
    price: 20,
    categoryId: "cat7",
    description: "Παραδοσιακός μπακλαβάς με φύλλο κρούστας",
    vatRate: 13,
    available: true,
    station: "dessert",
    modifierIds: [],
  },
  {
    id: "p26",
    name: "Τιραμισού",
    price: 14,
    categoryId: "cat7",
    description: "Κλασικό ιταλικό τιραμισού",
    vatRate: 13,
    available: true,
    station: "dessert",
    modifierIds: [],
  },
  {
    id: "p27",
    name: "Lemon Bar",
    price: 12,
    categoryId: "cat7",
    description: "Lemon bar με βουτυράτη βάση",
    vatRate: 13,
    available: true,
    station: "dessert",
    modifierIds: [],
  },
  {
    id: "p28",
    name: "Cheesecake",
    price: 14,
    categoryId: "cat7",
    description: "New York cheesecake",
    vatRate: 13,
    available: true,
    station: "dessert",
    modifierIds: [],
  },
];

export const initialOrders: Order[] = [];

// === Inventory Data ===

export const initialIngredients: Ingredient[] = [
  // Seafood
  {
    id: "ing1",
    name: "Τσιπούρα",
    unit: "kg",
    currentStock: 15,
    minStock: 5,
    costPerUnit: 18,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing2",
    name: "Μπαρμπούνι",
    unit: "kg",
    currentStock: 8,
    minStock: 3,
    costPerUnit: 22,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing3",
    name: "Φαγκρί",
    unit: "kg",
    currentStock: 6,
    minStock: 2,
    costPerUnit: 25,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing4",
    name: "Συναγρίδα",
    unit: "kg",
    currentStock: 2,
    minStock: 2,
    costPerUnit: 28,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing5",
    name: "Γαρίδες Θερμαϊκού",
    unit: "kg",
    currentStock: 10,
    minStock: 3,
    costPerUnit: 32,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing6",
    name: "Καλαμάρι",
    unit: "kg",
    currentStock: 12,
    minStock: 4,
    costPerUnit: 14,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing7",
    name: "Χταπόδι",
    unit: "kg",
    currentStock: 8,
    minStock: 3,
    costPerUnit: 16,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing8",
    name: "Λαβράκι φιλέτο",
    unit: "kg",
    currentStock: 6,
    minStock: 2,
    costPerUnit: 20,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing9",
    name: "Καβούρι",
    unit: "kg",
    currentStock: 1.5,
    minStock: 1,
    costPerUnit: 35,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing10",
    name: "Χτένια",
    unit: "kg",
    currentStock: 4,
    minStock: 2,
    costPerUnit: 28,
    supplierId: "sup1",
    category: "seafood",
  },
  {
    id: "ing11",
    name: "Όστρακα",
    unit: "kg",
    currentStock: 5,
    minStock: 2,
    costPerUnit: 18,
    supplierId: "sup1",
    category: "seafood",
  },
  // Vegetables
  {
    id: "ing12",
    name: "Ντομάτα",
    unit: "kg",
    currentStock: 20,
    minStock: 5,
    costPerUnit: 2.5,
    supplierId: "sup2",
    category: "vegetables",
  },
  {
    id: "ing13",
    name: "Μελιτζάνα",
    unit: "kg",
    currentStock: 8,
    minStock: 3,
    costPerUnit: 3,
    supplierId: "sup2",
    category: "vegetables",
  },
  {
    id: "ing14",
    name: "Πατάτα",
    unit: "kg",
    currentStock: 25,
    minStock: 8,
    costPerUnit: 1.5,
    supplierId: "sup2",
    category: "vegetables",
  },
  {
    id: "ing15",
    name: "Σέλινο",
    unit: "kg",
    currentStock: 5,
    minStock: 2,
    costPerUnit: 3,
    supplierId: "sup2",
    category: "vegetables",
  },
  {
    id: "ing16",
    name: "Κρεμμύδι",
    unit: "kg",
    currentStock: 15,
    minStock: 5,
    costPerUnit: 1.5,
    supplierId: "sup2",
    category: "vegetables",
  },
  {
    id: "ing17",
    name: "Λεμόνια",
    unit: "kg",
    currentStock: 10,
    minStock: 3,
    costPerUnit: 3,
    supplierId: "sup2",
    category: "vegetables",
  },
  {
    id: "ing18",
    name: "Μανιτάρια Portobello",
    unit: "kg",
    currentStock: 4,
    minStock: 2,
    costPerUnit: 8,
    supplierId: "sup2",
    category: "vegetables",
  },
  // Dairy
  {
    id: "ing19",
    name: "Αυγά",
    unit: "pcs",
    currentStock: 60,
    minStock: 20,
    costPerUnit: 0.35,
    supplierId: "sup3",
    category: "dairy",
  },
  {
    id: "ing20",
    name: "Φέτα",
    unit: "kg",
    currentStock: 5,
    minStock: 2,
    costPerUnit: 12,
    supplierId: "sup3",
    category: "dairy",
  },
  // Dry
  {
    id: "ing21",
    name: "Ελαιόλαδο",
    unit: "lt",
    currentStock: 20,
    minStock: 5,
    costPerUnit: 8,
    category: "dry",
  },
  {
    id: "ing22",
    name: "Αλεύρι",
    unit: "kg",
    currentStock: 10,
    minStock: 3,
    costPerUnit: 1.2,
    category: "dry",
  },
  {
    id: "ing23",
    name: "Ζυμαρικά Λιγκουίνι",
    unit: "kg",
    currentStock: 8,
    minStock: 3,
    costPerUnit: 3.5,
    category: "dry",
  },
  {
    id: "ing24",
    name: "Σάλτσα Ντομάτας",
    unit: "lt",
    currentStock: 10,
    minStock: 3,
    costPerUnit: 2.5,
    category: "dry",
  },
  {
    id: "ing25",
    name: "Πελτές",
    unit: "kg",
    currentStock: 5,
    minStock: 2,
    costPerUnit: 4,
    category: "dry",
  },
  {
    id: "ing26",
    name: "Ταραμάς",
    unit: "kg",
    currentStock: 3,
    minStock: 1,
    costPerUnit: 25,
    category: "dry",
  },
  {
    id: "ing27",
    name: "Φύλλο Κρούστας",
    unit: "pcs",
    currentStock: 20,
    minStock: 5,
    costPerUnit: 1.5,
    category: "dry",
  },
  {
    id: "ing28",
    name: "Μυρωδικά mix",
    unit: "kg",
    currentStock: 2,
    minStock: 0.5,
    costPerUnit: 15,
    category: "dry",
  },
  // Drinks
  {
    id: "ing29",
    name: "Κρασί Λευκό χύμα",
    unit: "lt",
    currentStock: 30,
    minStock: 10,
    costPerUnit: 4,
    supplierId: "sup4",
    category: "drinks",
  },
  {
    id: "ing30",
    name: "Κρασί Κόκκινο χύμα",
    unit: "lt",
    currentStock: 20,
    minStock: 8,
    costPerUnit: 4.5,
    supplierId: "sup4",
    category: "drinks",
  },
];

export const initialRecipes: Recipe[] = [
  // p1 - Καρπάτσιο Λαβρακιού
  {
    id: "rec1",
    productId: "p1",
    ingredients: [
      { ingredientId: "ing8", quantity: 0.15, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.02, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.05, unit: "kg" },
    ],
    prepTime: 10,
    portionSize: "1 μερίδα",
  },
  // p2 - Καρπάτσιο Μπαρμπουνιού
  {
    id: "rec2",
    productId: "p2",
    ingredients: [
      { ingredientId: "ing2", quantity: 0.18, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.02, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.05, unit: "kg" },
    ],
    prepTime: 10,
    portionSize: "1 μερίδα",
  },
  // p3 - Ταρτάρ Γαρίδας
  {
    id: "rec3",
    productId: "p3",
    ingredients: [
      { ingredientId: "ing5", quantity: 0.18, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.02, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.03, unit: "kg" },
      { ingredientId: "ing28", quantity: 0.005, unit: "kg" },
    ],
    prepTime: 12,
    portionSize: "1 μερίδα",
  },
  // p4 - Ταραμοσαλάτα Λευκή
  {
    id: "rec4",
    productId: "p4",
    ingredients: [
      { ingredientId: "ing26", quantity: 0.08, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.03, unit: "kg" },
    ],
    prepTime: 15,
    portionSize: "1 μερίδα",
  },
  // p5 - Μελιτζανοσαλάτα
  {
    id: "rec5",
    productId: "p5",
    ingredients: [
      { ingredientId: "ing13", quantity: 0.25, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.03, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.02, unit: "kg" },
    ],
    prepTime: 30,
    portionSize: "1 μερίδα",
  },
  // p6 - Καβουροσαλάτα
  {
    id: "rec6",
    productId: "p6",
    ingredients: [
      { ingredientId: "ing9", quantity: 0.15, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.02, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.03, unit: "kg" },
      { ingredientId: "ing12", quantity: 0.05, unit: "kg" },
    ],
    prepTime: 20,
    portionSize: "1 μερίδα",
  },
  // p7 - Χτένια Ωμά
  {
    id: "rec7",
    productId: "p7",
    ingredients: [
      { ingredientId: "ing10", quantity: 0.2, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.02, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.03, unit: "kg" },
    ],
    prepTime: 8,
    portionSize: "1 μερίδα",
  },
  // p8 - Σαγανάκι Γαρίδες
  {
    id: "rec8",
    productId: "p8",
    ingredients: [
      { ingredientId: "ing5", quantity: 0.2, unit: "kg" },
      { ingredientId: "ing20", quantity: 0.05, unit: "kg" },
      { ingredientId: "ing12", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.03, unit: "lt" },
      { ingredientId: "ing24", quantity: 0.05, unit: "lt" },
    ],
    prepTime: 15,
    portionSize: "1 μερίδα",
  },
  // p9 - Αχνιστά Όστρακα
  {
    id: "rec9",
    productId: "p9",
    ingredients: [
      { ingredientId: "ing11", quantity: 0.3, unit: "kg" },
      { ingredientId: "ing29", quantity: 0.1, unit: "lt" },
      { ingredientId: "ing21", quantity: 0.02, unit: "lt" },
      { ingredientId: "ing28", quantity: 0.005, unit: "kg" },
    ],
    prepTime: 12,
    portionSize: "1 μερίδα",
  },
  // p10 - Καλαμαράκια Τηγανητά
  {
    id: "rec10",
    productId: "p10",
    ingredients: [
      { ingredientId: "ing6", quantity: 0.25, unit: "kg" },
      { ingredientId: "ing22", quantity: 0.05, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.1, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.03, unit: "kg" },
    ],
    prepTime: 10,
    portionSize: "1 μερίδα",
  },
  // p11 - Γαρίδες Τηγανητές
  {
    id: "rec11",
    productId: "p11",
    ingredients: [
      { ingredientId: "ing5", quantity: 0.25, unit: "kg" },
      { ingredientId: "ing22", quantity: 0.05, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.1, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.03, unit: "kg" },
    ],
    prepTime: 10,
    portionSize: "1 μερίδα",
  },
  // p12 - Τσιπούρα (per kg)
  {
    id: "rec12",
    productId: "p12",
    ingredients: [
      { ingredientId: "ing1", quantity: 1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing28", quantity: 0.01, unit: "kg" },
    ],
    prepTime: 20,
    portionSize: "1 κιλό",
  },
  // p13 - Μπαρμπούνι (per kg)
  {
    id: "rec13",
    productId: "p13",
    ingredients: [
      { ingredientId: "ing2", quantity: 1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing28", quantity: 0.01, unit: "kg" },
    ],
    prepTime: 15,
    portionSize: "1 κιλό",
  },
  // p14 - Φαγκρί (per kg)
  {
    id: "rec14",
    productId: "p14",
    ingredients: [
      { ingredientId: "ing3", quantity: 1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing28", quantity: 0.01, unit: "kg" },
    ],
    prepTime: 25,
    portionSize: "1 κιλό",
  },
  // p15 - Συναγρίδα (per kg)
  {
    id: "rec15",
    productId: "p15",
    ingredients: [
      { ingredientId: "ing4", quantity: 1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing28", quantity: 0.01, unit: "kg" },
    ],
    prepTime: 25,
    portionSize: "1 κιλό",
  },
  // p16 - Γαρίδες Θερμαϊκού (per kg)
  {
    id: "rec16",
    productId: "p16",
    ingredients: [
      { ingredientId: "ing5", quantity: 1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
    ],
    prepTime: 15,
    portionSize: "1 κιλό",
  },
  // p17 - Καλαμάρι (per kg)
  {
    id: "rec17",
    productId: "p17",
    ingredients: [
      { ingredientId: "ing6", quantity: 1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing28", quantity: 0.01, unit: "kg" },
    ],
    prepTime: 20,
    portionSize: "1 κιλό",
  },
  // p18 - Χταπόδι (per kg)
  {
    id: "rec18",
    productId: "p18",
    ingredients: [
      { ingredientId: "ing7", quantity: 1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
    ],
    prepTime: 45,
    portionSize: "1 κιλό",
  },
  // p19 - Ψαρόσουπα
  {
    id: "rec19",
    productId: "p19",
    ingredients: [
      { ingredientId: "ing1", quantity: 0.5, unit: "kg" },
      { ingredientId: "ing3", quantity: 0.3, unit: "kg" },
      { ingredientId: "ing14", quantity: 0.2, unit: "kg" },
      { ingredientId: "ing15", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing16", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing17", quantity: 0.15, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing19", quantity: 2, unit: "pcs" },
    ],
    prepTime: 60,
    portionSize: "4 μερίδες",
  },
  // p20 - Φρικασέ
  {
    id: "rec20",
    productId: "p20",
    ingredients: [
      { ingredientId: "ing1", quantity: 0.6, unit: "kg" },
      { ingredientId: "ing5", quantity: 0.3, unit: "kg" },
      { ingredientId: "ing15", quantity: 0.15, unit: "kg" },
      { ingredientId: "ing16", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing17", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.08, unit: "lt" },
      { ingredientId: "ing19", quantity: 3, unit: "pcs" },
      { ingredientId: "ing28", quantity: 0.02, unit: "kg" },
    ],
    prepTime: 50,
    portionSize: "4 μερίδες",
  },
  // p21 - Κοκκινιστό
  {
    id: "rec21",
    productId: "p21",
    ingredients: [
      { ingredientId: "ing1", quantity: 0.5, unit: "kg" },
      { ingredientId: "ing6", quantity: 0.3, unit: "kg" },
      { ingredientId: "ing24", quantity: 0.3, unit: "lt" },
      { ingredientId: "ing25", quantity: 0.05, unit: "kg" },
      { ingredientId: "ing16", quantity: 0.15, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.08, unit: "lt" },
      { ingredientId: "ing28", quantity: 0.02, unit: "kg" },
    ],
    prepTime: 55,
    portionSize: "4 μερίδες",
  },
  // p22 - Πλακί
  {
    id: "rec22",
    productId: "p22",
    ingredients: [
      { ingredientId: "ing3", quantity: 0.8, unit: "kg" },
      { ingredientId: "ing12", quantity: 0.3, unit: "kg" },
      { ingredientId: "ing16", quantity: 0.15, unit: "kg" },
      { ingredientId: "ing14", quantity: 0.3, unit: "kg" },
      { ingredientId: "ing15", quantity: 0.1, unit: "kg" },
      { ingredientId: "ing21", quantity: 0.1, unit: "lt" },
      { ingredientId: "ing24", quantity: 0.2, unit: "lt" },
      { ingredientId: "ing28", quantity: 0.02, unit: "kg" },
    ],
    prepTime: 60,
    portionSize: "4 μερίδες",
  },
  // p23 - Γαριδομακαρονάδα
  {
    id: "rec23",
    productId: "p23",
    ingredients: [
      { ingredientId: "ing5", quantity: 0.3, unit: "kg" },
      { ingredientId: "ing23", quantity: 0.2, unit: "kg" },
      { ingredientId: "ing24", quantity: 0.1, unit: "lt" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing16", quantity: 0.03, unit: "kg" },
    ],
    prepTime: 25,
    portionSize: "1 μερίδα",
  },
  // p24 - Αστακομακαρονάδα
  {
    id: "rec24",
    productId: "p24",
    ingredients: [
      { ingredientId: "ing5", quantity: 0.4, unit: "kg" },
      { ingredientId: "ing23", quantity: 0.25, unit: "kg" },
      { ingredientId: "ing24", quantity: 0.15, unit: "lt" },
      { ingredientId: "ing21", quantity: 0.05, unit: "lt" },
      { ingredientId: "ing16", quantity: 0.03, unit: "kg" },
      { ingredientId: "ing12", quantity: 0.08, unit: "kg" },
      { ingredientId: "ing28", quantity: 0.01, unit: "kg" },
    ],
    prepTime: 35,
    portionSize: "1 μερίδα",
  },
  // p25 - Μπακλαβάς
  {
    id: "rec25",
    productId: "p25",
    ingredients: [
      { ingredientId: "ing27", quantity: 3, unit: "pcs" },
      { ingredientId: "ing19", quantity: 1, unit: "pcs" },
    ],
    prepTime: 5,
    portionSize: "1 μερίδα",
  },
  // p26 - Τιραμισού
  {
    id: "rec26",
    productId: "p26",
    ingredients: [{ ingredientId: "ing19", quantity: 2, unit: "pcs" }],
    prepTime: 5,
    portionSize: "1 μερίδα",
  },
  // p27 - Lemon Bar
  {
    id: "rec27",
    productId: "p27",
    ingredients: [
      { ingredientId: "ing19", quantity: 1, unit: "pcs" },
      { ingredientId: "ing17", quantity: 0.05, unit: "kg" },
      { ingredientId: "ing22", quantity: 0.03, unit: "kg" },
    ],
    prepTime: 5,
    portionSize: "1 μερίδα",
  },
  // p28 - Cheesecake
  {
    id: "rec28",
    productId: "p28",
    ingredients: [{ ingredientId: "ing19", quantity: 1, unit: "pcs" }],
    prepTime: 5,
    portionSize: "1 μερίδα",
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: "sup1",
    name: "Ιχθυοπωλείο Θερμαϊκός",
    phone: "2310-555-001",
    categories: ["seafood"],
  },
  {
    id: "sup2",
    name: "Λαχαναγορά Κεντρική",
    phone: "2310-555-002",
    categories: ["vegetables"],
  },
  {
    id: "sup3",
    name: "Γαλακτοκομικά Μακεδονίας",
    phone: "2310-555-003",
    categories: ["dairy"],
  },
  {
    id: "sup4",
    name: "Οινοποιείο Τσάνταλη",
    phone: "2310-555-004",
    categories: ["drinks"],
  },
];

export const initialSupplierOrders: SupplierOrder[] = [];

export const initialWasteLog: WasteEntry[] = [
  {
    id: "w1",
    ingredientId: "ing5",
    quantity: 0.5,
    reason: "expired",
    date: "2026-03-25T10:00:00.000Z",
    notes: "Γαρίδες ημέρας - δεν πουλήθηκαν",
  },
  {
    id: "w2",
    ingredientId: "ing12",
    quantity: 2,
    reason: "damaged",
    date: "2026-03-25T11:30:00.000Z",
    notes: "Χτυπημένες ντομάτες από μεταφορά",
  },
  {
    id: "w3",
    ingredientId: "ing11",
    quantity: 0.3,
    reason: "overproduction",
    date: "2026-03-26T21:00:00.000Z",
    notes: "Περίσσεψαν από αχνιστά",
  },
  {
    id: "w4",
    ingredientId: "ing6",
    quantity: 0.2,
    reason: "returned",
    date: "2026-03-26T20:30:00.000Z",
    notes: "Πελάτης επέστρεψε πιάτο",
  },
];

// Helper function to generate unique IDs
export function generateId(): string {
  return Math.random().toString(36).substring(2, 11);
}

// Helper to format price in Greek format
export function formatPrice(price: number): string {
  return new Intl.NumberFormat("el-GR", {
    style: "currency",
    currency: "EUR",
  }).format(price);
}

// Helper to format date/time in Greek
export function formatDateTime(dateString: string): string {
  return new Intl.DateTimeFormat("el-GR", {
    hour: "2-digit",
    minute: "2-digit",
    day: "2-digit",
    month: "2-digit",
  }).format(new Date(dateString));
}

export function formatTime(dateString: string): string {
  return new Intl.DateTimeFormat("el-GR", {
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(dateString));
}
